# Pandas (DataFrames)

This Notebook includes the following contents:

* Introduction to DataFrames.
* Installation and Import NumPy and Pandas.
* Creating a DataFrames.

  - Create a DataFrame from a **dictionary of lists**.
  - Create a DataFrame from a **list of dictionaries**.
  
* Aggregation Functions

# Introduction to DataFrames

*  `Pandas DataFrame`: A DataFrame is a two-dimensional labeled data structure with columns of potentially different data types. It can be thought of as a collection of Series objects, where each Series represents a column in the DataFrame.

# Installation and Import NumPy and Pandas

In [ ]:
# pip install pandas

In [1]:
import numpy as np
import pandas as pd

# Creating a DataFrames

In [2]:
#If we were to use a series for this data, this is how it would look like:

data = {'Name': ['Omar', 'Mohammad', 'Ross'],
        'Age': [25, 30, 35],
        'Salary': [50000, 60000, 70000]}

df = pd.Series(data)
df

Name      [Omar, Mohammad, Ross]
Age                 [25, 30, 35]
Salary     [50000, 60000, 70000]
dtype: object

In [3]:
# However, using a DataFrame it would look like this:

data = {'Name': ['Omar', 'Mohammad', 'Ross'],
        'Age': [25, 30, 35],
        'Salary': [50000, 60000, 70000]
        }

df = pd.DataFrame(data)
df

       Name  Age  Salary
0      Omar   25   50000
1  Mohammad   30   60000
2      Ross   35   70000



---

In [ ]:
# Create a DataFrame from a list of dictionaries


data = [{'Name': 'Ayman', 'Age': 28, 'Salary': 55000}, # it represents the first row
        {'Name': 'Omar', 'Age': 30, 'Salary': 80000},# it represents the second row
        {'Name': 'Mohammad', 'Age': 30, 'Salary': 60000} # it represents the third row
        ]
df = pd.DataFrame(data)
df

       Name  Age  Salary Namee
0     Ayman   28   55000   NaN
1       NaN   30   80000  Omar
2  Mohammad   30   60000   NaN

In [6]:
data = [{'Name': 'Ayman', 'Age': 28, 'Salary': 55000}, # it represents the first row
        {'Name': 'Omar', 'Age': 30, 'Salary': 80000},# it represents the second row
        {'Namee': 'Mohammad', 'Age': 30, 'Salary': 60000} # it represents the third row
        ]
df = pd.DataFrame(data)

Task 1:

Create a dataframe from a list of four dictionaries with custom columns like product, price, quantity, and discount. Fill in the values as you like!

In [16]:
# List of dictionaries
data = [
    {'product': 'Laptop',     'price': 1200, 'quantity': 5, 'discount': 0.10},
    {'product': 'Headphones', 'price': 150,  'quantity': 15, 'discount': 0.20},
    {'product': 'Mouse',      'price': 25,   'quantity': 50, 'discount': 0.0},
    {'product': 'Keyboard',   'price': 70,   'quantity': 30, 'discount': 0.25}
]

# Create the DataFrame
df = pd.DataFrame(data)

# Display the result
df

      product  price  quantity  discount
0      Laptop   1200         5      0.10
1  Headphones    150        15      0.20
2       Mouse     25        50      0.00
3    Keyboard     70        30      0.25



---

# Aggregation Functions

In [8]:
data = [{'Name': 'Ayman', 'Age': 28, 'Salary': 55000}, # it represents the first row
        {'Name': 'Omar', 'Age': 30, 'Salary': 80000},# it represents the second row
        {'Name': 'Mohammad', 'Age': 30, 'Salary': 60000} # it represents the third row
        ]
df = pd.DataFrame(data)

df

       Name  Age  Salary
0     Ayman   28   55000
1      Omar   30   80000
2  Mohammad   30   60000

In [9]:
df['Age'].mean()

np.float64(29.333333333333332)

In [13]:
mean_age = df['Age'].mean().round(1)
print(f"Mean Age: {mean_age}")

mean_age = int(df['Age'].mean().round(0))
print(f"Mean Age: {mean_age}")

mean_age = round(df['Age'].mean(), 1)
print(f"Mean Age: {mean_age}")

Mean Age: 29.3
Mean Age: 29
Mean Age: 29.3

In [14]:
# Sum of all salaries
total_salary = df['Salary'].sum()
print(f"Total Salary: {total_salary}")

Total Salary: 195000

Task 2:

Find the median of discount column.

In [17]:
median = round(df['discount'].median(), 2)
print("Median Discount: ", median*100, "%")

Median Discount:  15.0 %

# Great Job ❤