# Pandas (Selection and Indexing)

This Notebook includes the following contents:

* Access Single Column
* Access Multiple Columns
* Selecting a row (iloc , loc)
* Filtering the data

# Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name': ['Omar', 'Mohammad', 'Tuqa', 'Zaina', 'Malik' ],
    'Age': [25, 30, 35, 20, 45],
    'City': ['Amman', 'Damascus', 'Damascus', 'Yafa', 'Irbid'],
    'Score': [85.5, 90.3, 78.9, 92.5, 88.0]
}

df = pd.DataFrame(data)
df

       Name  Age      City  Score
0      Omar   25     Amman   85.5
1  Mohammad   30  Damascus   90.3
2      Tuqa   35  Damascus   78.9
3     Zaina   20      Yafa   92.5
4     Malik   45     Irbid   88.0

# Access Single Column

In [3]:
age_column = df['Age']
age_column

0    25
1    30
2    35
3    20
4    45
Name: Age, dtype: int64

In [4]:
df.Name

0        Omar
1    Mohammad
2        Tuqa
3       Zaina
4       Malik
Name: Name, dtype: object

# Access Multiple Columns

In [5]:
my_columns = ['Name', 'Score']
subset = df[my_columns]
subset

       Name  Score
0      Omar   85.5
1  Mohammad   90.3
2      Tuqa   78.9
3     Zaina   92.5
4     Malik   88.0

In [6]:
df[['Name','Age']]

       Name  Age
0      Omar   25
1  Mohammad   30
2      Tuqa   35
3     Zaina   20
4     Malik   45

Task 1:

Access name column and save it to a variable.

Take a subset of the data frame (name, score) and also save it to a variable.


---

In [ ]:
name_column = df['Name']
print(name_column)
subset = df[['Name', 'Score']]
print(subset)

<class 'pandas.core.series.Series'>
       Name  Score
0      Omar   85.5
1  Mohammad   90.3
2      Tuqa   78.9
3     Zaina   92.5
4     Malik   88.0

In [10]:
type(name_column)

pandas.core.series.Series

# Selecting a Row

In [11]:
df

       Name  Age      City  Score
0      Omar   25     Amman   85.5
1  Mohammad   30  Damascus   90.3
2      Tuqa   35  Damascus   78.9
3     Zaina   20      Yafa   92.5
4     Malik   45     Irbid   88.0

In [17]:
# Selecting Rows
first_row = df.iloc[0] # it stands for integer location
first_row

Name      Omar
Age         25
City     Amman
Score     85.5
Name: 0, dtype: object

In [18]:
df_1 = pd.DataFrame(first_row)
df_1

           0
Name    Omar
Age       25
City   Amman
Score   85.5

In [19]:
first_three_rows = df.iloc[0:3]
first_three_rows

       Name  Age      City  Score
0      Omar   25     Amman   85.5
1  Mohammad   30  Damascus   90.3
2      Tuqa   35  Damascus   78.9

In [20]:
df.iloc[[0, 4, 1]] #select the specific rows

       Name  Age      City  Score
0      Omar   25     Amman   85.5
4     Malik   45     Irbid   88.0
1  Mohammad   30  Damascus   90.3

In [21]:
df.iloc[[0,2]]

   Name  Age      City  Score
0  Omar   25     Amman   85.5
2  Tuqa   35  Damascus   78.9

In [22]:
df.iloc[0:2]

       Name  Age      City  Score
0      Omar   25     Amman   85.5
1  Mohammad   30  Damascus   90.3

In [23]:
my_rows = [0, 2, 4]
specific_rows = df.iloc[my_rows]
specific_rows

    Name  Age      City  Score
0   Omar   25     Amman   85.5
2   Tuqa   35  Damascus   78.9
4  Malik   45     Irbid   88.0

In [24]:
# select specific rows and columns using iloc
rows_columns = df.iloc[[0,1], [0,2]]
rows_columns

       Name      City
0      Omar     Amman
1  Mohammad  Damascus

In [25]:
df.iloc[[0,4], [1,3]]

   Age  Score
0   25   85.5
4   45   88.0

In [26]:
df.iloc[[0,4], 1]

0    25
4    45
Name: Age, dtype: int64

In [27]:
df.iloc[0:3, [2,0]]

       City      Name
0     Amman      Omar
1  Damascus  Mohammad
2  Damascus      Tuqa

In [32]:
# select specific rows and columns using loc
rows_columns = df.loc[[0,1] , ["Name", "Age"]]
rows_columns

       Name  Age
0      Omar   25
1  Mohammad   30

In [33]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [34]:
df_custom_index = df.set_index('Name')  #what happened here?
df_custom_index

          Age      City  Score
Name
Omar       25     Amman   85.5
Mohammad   30  Damascus   90.3
Tuqa       35  Damascus   78.9
Zaina      20      Yafa   92.5
Malik      45     Irbid   88.0

In [44]:
df_custom_index.loc[['Omar', 'Tuqa'], ['Age', 'City']]

      Age      City
Name
Omar   25     Amman
Tuqa   35  Damascus

In [47]:
dd = df_custom_index.reset_index()
dd

       Name  Age      City  Score
0      Omar   25     Amman   85.5
1  Mohammad   30  Damascus   90.3
2      Tuqa   35  Damascus   78.9
3     Zaina   20      Yafa   92.5
4     Malik   45     Irbid   88.0

In [50]:
df_custom_index = df_custom_index.reset_index(drop = True) #Now here, what happened?
df_custom_index

   Age      City  Score
0   25     Amman   85.5
1   30  Damascus   90.3
2   35  Damascus   78.9
3   20      Yafa   92.5
4   45     Irbid   88.0

In [51]:
df.set_index('Name',inplace = True)
df

          Age      City  Score
Name
Omar       25     Amman   85.5
Mohammad   30  Damascus   90.3
Tuqa       35  Damascus   78.9
Zaina      20      Yafa   92.5
Malik      45     Irbid   88.0

In [52]:
# If a DataFrame has a custom index

row_by_custom_label = df.loc['Omar']
row_by_custom_label

Age         25
City     Amman
Score     85.5
Name: Omar, dtype: object

In [53]:
df.reset_index()

       Name  Age      City  Score
0      Omar   25     Amman   85.5
1  Mohammad   30  Damascus   90.3
2      Tuqa   35  Damascus   78.9
3     Zaina   20      Yafa   92.5
4     Malik   45     Irbid   88.0

# Filtering the data

In [54]:
data = {
    'Name': ['Omar', 'Mohammad', 'Tuqa', 'Zaina', 'Malik' ],
    'Age': [25, 30, 35, 20, 45],
    'City': ['Amman', 'Damascus', 'Damascus', 'Yafa', 'Irbid'],
    'Score': [85.5, 90.3, 78.9, 92.5, 88.0]
}

df = pd.DataFrame(data)

In [55]:
df

       Name  Age      City  Score
0      Omar   25     Amman   85.5
1  Mohammad   30  Damascus   90.3
2      Tuqa   35  Damascus   78.9
3     Zaina   20      Yafa   92.5
4     Malik   45     Irbid   88.0

In [56]:
df['Age'] > 30

0    False
1    False
2     True
3    False
4     True
Name: Age, dtype: bool

In [57]:
df[df['Age'] > 30]

    Name  Age      City  Score
2   Tuqa   35  Damascus   78.9
4  Malik   45     Irbid   88.0

In [59]:
df["City"] == "Yafa"

0    False
1    False
2    False
3     True
4    False
Name: City, dtype: bool

In [60]:
df[df["City"]=="Yafa"]

    Name  Age  City  Score
3  Zaina   20  Yafa   92.5

In [61]:
df[(df["City"]=="Damascus") | (df["Age"]>35)]

       Name  Age      City  Score
1  Mohammad   30  Damascus   90.3
2      Tuqa   35  Damascus   78.9
4     Malik   45     Irbid   88.0

In [62]:
df[(df["City"]=="Damascus") & (df["Age"]>30)]

   Name  Age      City  Score
2  Tuqa   35  Damascus   78.9

In [65]:
df[df["City"]=="Zarqa"]

Empty DataFrame
Columns: [Name, Age, City, Score]
Index: []

In [66]:
df[(df['Name'] == 'Mohammad') | (df['Name'] == 'Omar')  | (df['Name'] == 'Tuqa')]

       Name  Age      City  Score
0      Omar   25     Amman   85.5
1  Mohammad   30  Damascus   90.3
2      Tuqa   35  Damascus   78.9

In [67]:
# using isin
names = ['Tuqa' , 'Omar' , 'Zaina', 'batool']

multiple_values = df[ df['Name'].isin(names)  ]
multiple_values

    Name  Age      City  Score
0   Omar   25     Amman   85.5
2   Tuqa   35  Damascus   78.9
3  Zaina   20      Yafa   92.5

Task 2:

Write a pandas code to filter the data based on two conditions price is greater than or equal 800
and   quantity is greater than or equal 5

In [68]:
data = [
    {'Product': 'Laptop', 'Price': 1200, 'Quantity': 5, 'Discount': 10},
    {'Product': 'Tablet', 'Price': 600, 'Quantity': 10, 'Discount': 15},
    {'Product': 'Smartphone', 'Price': 800, 'Quantity': 7, 'Discount': 5},
    {'Product': 'Monitor', 'Price': 300, 'Quantity': 12, 'Discount': 20}
]

products_df = pd.DataFrame(data)
products_df

      Product  Price  Quantity  Discount
0      Laptop   1200         5        10
1      Tablet    600        10        15
2  Smartphone    800         7         5
3     Monitor    300        12        20

In [71]:
products_df[(products_df["Price"] >= 800) & (products_df["Quantity"] <= 5)]

  Product  Price  Quantity  Discount
0  Laptop   1200         5        10

# Great Job ❤