# Pandas (Updating, Removing, Adding rows and columns)

This Notebook includes the following contents:

* Set and Reset all values in column.
* Updating column to some calculated values.
* Add a new column.
* Updating singel value for a specific row

* More Examples about adding columns

* Rename Columns

* Add column by condition (where)

* Add column by multiple conditions (apply)

* Drop Columns
  
  - Drop One Column.
  - Drop Multiple Columns.

* Appending New Rows.

* Drop Rows

  - Drop Multiple Rows.
  - Dropping using condition.

* Quick Reviews

# Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name'      :   ['Emad', 'Qusai', 'Mona', 'Ibraheem', 'Malik'],
    'Age'       :   [25, 30, 35, 20, 45],
    'City'      :   ['Amman', 'Damascus', 'Damascus', 'Yafa', 'Irbid'],
    'Score'     :   [85.5, 90.3, 78.9, 92.5, 88.0]
}

df = pd.DataFrame(data)
df

       Name  Age      City  Score
0      Emad   25     Amman   85.5
1     Qusai   30  Damascus   90.3
2      Mona   35  Damascus   78.9
3  Ibraheem   20      Yafa   92.5
4     Malik   45     Irbid   88.0

# Set and Reset all values in column.

In [3]:
# Set all values in 'Age' column to 50
df['Age'] = 50
df

       Name  Age      City  Score
0      Emad   50     Amman   85.5
1     Qusai   50  Damascus   90.3
2      Mona   50  Damascus   78.9
3  Ibraheem   50      Yafa   92.5
4     Malik   50     Irbid   88.0

In [7]:
# Reset 'Age' for further examples
df['Age'] = [25, 30, 35, 40, 45]
df

       Name  Age      City  Score
0      Emad   25     Amman   85.5
1     Qusai   30  Damascus   90.3
2      Mona   35  Damascus   78.9
3  Ibraheem   40      Yafa   92.5
4     Malik   45     Irbid   88.0

# Task 1: Think of a another way to reset these values.

Hint: it's something we used last session!

In [8]:
data = {
    'Name'  : ['Emad', 'Qusai', 'Mona', 'Ibraheem', 'Malik'],
    'Age'   : [25, 30, 35, 20, 45],
    'City'  : ['Amman', 'Damascus', 'Damascus', 'Yafa', 'Irbid'],
    'Score' : [85.5, 90.3, 78.9, 92.5, 88.0]
}

df = pd.DataFrame(data)
print("Original DataFrame: \n")
df

Original DataFrame:

       Name  Age      City  Score
0      Emad   25     Amman   85.5
1     Qusai   30  Damascus   90.3
2      Mona   35  Damascus   78.9
3  Ibraheem   20      Yafa   92.5
4     Malik   45     Irbid   88.0

In [9]:
# Step 1: Save a copy of the original Age column
original_age = df['Age'].copy()
original_age

0    25
1    30
2    35
3    20
4    45
Name: Age, dtype: int64

In [10]:
# Step 2: Modify Age column (e.g., set all to 35)
df['Age'] = 35
print("Modified DataFrame:")
df

Modified DataFrame:

       Name  Age      City  Score
0      Emad   35     Amman   85.5
1     Qusai   35  Damascus   90.3
2      Mona   35  Damascus   78.9
3  Ibraheem   35      Yafa   92.5
4     Malik   35     Irbid   88.0

In [11]:
# Step 3: Reset Age column to original
df['Age'] = original_age
print("\nReset DataFrame:")
df

Reset DataFrame:

       Name  Age      City  Score
0      Emad   25     Amman   85.5
1     Qusai   30  Damascus   90.3
2      Mona   35  Damascus   78.9
3  Ibraheem   20      Yafa   92.5
4     Malik   45     Irbid   88.0

# Updating column to some calculated values

In [20]:
# Updating 'Score' column to some calculated values
df['Score'] = df['Score'] + 3

In [21]:
df

       Name  Age      City  Score
0      Emad   25     Amman   88.5
1     Qusai   30  Damascus   93.3
2      Mona   35  Damascus   81.9
3  Ibraheem   20      Yafa   95.5
4     Malik   45     Irbid   91.0

In [22]:
df['Score New'] = df['Score'] - 3

In [23]:
df

       Name  Age      City  Score  Score New
0      Emad   25     Amman   88.5       85.5
1     Qusai   30  Damascus   93.3       90.3
2      Mona   35  Damascus   81.9       78.9
3  Ibraheem   20      Yafa   95.5       92.5
4     Malik   45     Irbid   91.0       88.0

# Updating single value for a specific row

In [24]:
# updating single value for a specific row
df.loc[0 , "Name"] = "Sham"
df

       Name  Age      City  Score  Score New
0      Sham   25     Amman   88.5       85.5
1     Qusai   30  Damascus   93.3       90.3
2      Mona   35  Damascus   81.9       78.9
3  Ibraheem   20      Yafa   95.5       92.5
4     Malik   45     Irbid   91.0       88.0

In [25]:
df.iloc[0,0] = "Emad"
df

       Name  Age      City  Score  Score New
0      Emad   25     Amman   88.5       85.5
1     Qusai   30  Damascus   93.3       90.3
2      Mona   35  Damascus   81.9       78.9
3  Ibraheem   20      Yafa   95.5       92.5
4     Malik   45     Irbid   91.0       88.0

In [26]:
# more sophisticated way
df.loc[df['Name'] == 'Emad' , ['Name','Age']] = ['Omar' ,30]
df

       Name  Age      City  Score  Score New
0      Omar   30     Amman   88.5       85.5
1     Qusai   30  Damascus   93.3       90.3
2      Mona   35  Damascus   81.9       78.9
3  Ibraheem   20      Yafa   95.5       92.5
4     Malik   45     Irbid   91.0       88.0

# Task 2:

Change the third entry's info as follows:

Name -> Lamees

City -> Aleppo

Score -> 85.2

In [27]:
df.loc[2, ['Name', 'City', 'Score']] = ['Lamees', 'Aleppo', 85.2]
df

       Name  Age      City  Score  Score New
0      Omar   30     Amman   88.5       85.5
1     Qusai   30  Damascus   93.3       90.3
2    Lamees   35    Aleppo   85.2       78.9
3  Ibraheem   20      Yafa   95.5       92.5
4     Malik   45     Irbid   91.0       88.0

# Add a new column

In [64]:
data = {
    'Name': ['Emad', 'Qusai', 'Mona', 'Ibraheem', 'Malik'],
    'Age': [25, 30, 35, 20, 45],
    'City': ['Amman', 'Damascus', 'Damascus', 'Yafa', 'Irbid'],
    'Score': [85.5, 90.3, 78.9, 92.5, 88.0]
}

df = pd.DataFrame(data)

In [65]:
df

       Name  Age      City  Score
0      Emad   25     Amman   85.5
1     Qusai   30  Damascus   90.3
2      Mona   35  Damascus   78.9
3  Ibraheem   20      Yafa   92.5
4     Malik   45     Irbid   88.0

In [66]:
df['Score']>= 85

0     True
1     True
2    False
3     True
4     True
Name: Score, dtype: bool

In [67]:
df[df['Score']>= 85]

       Name  Age      City  Score
0      Emad   25     Amman   85.5
1     Qusai   30  Damascus   90.3
3  Ibraheem   20      Yafa   92.5
4     Malik   45     Irbid   88.0

In [68]:
# Adding a New Column
df['Passed'] = df['Score'] >= 85

In [69]:
df

       Name  Age      City  Score  Passed
0      Emad   25     Amman   85.5    True
1     Qusai   30  Damascus   90.3    True
2      Mona   35  Damascus   78.9   False
3  Ibraheem   20      Yafa   92.5    True
4     Malik   45     Irbid   88.0    True

In [70]:
df["Passed"] = df["Score"].apply(lambda x: "Yes" if x >= 85 else "No")
df

       Name  Age      City  Score Passed
0      Emad   25     Amman   85.5    Yes
1     Qusai   30  Damascus   90.3    Yes
2      Mona   35  Damascus   78.9     No
3  Ibraheem   20      Yafa   92.5    Yes
4     Malik   45     Irbid   88.0    Yes

In [71]:
df["num"] = [1,2,3,4,5]
df

       Name  Age      City  Score Passed  num
0      Emad   25     Amman   85.5    Yes    1
1     Qusai   30  Damascus   90.3    Yes    2
2      Mona   35  Damascus   78.9     No    3
3  Ibraheem   20      Yafa   92.5    Yes    4
4     Malik   45     Irbid   88.0    Yes    5

# Task 3:

Add a column for the Youth category, where individuals aged 25 and below are considered Youth. Then print the recods of the Youth individuals only.

In [72]:
df['Youth'] = df['Age'] <= 25
df

       Name  Age      City  Score Passed  num  Youth
0      Emad   25     Amman   85.5    Yes    1   True
1     Qusai   30  Damascus   90.3    Yes    2  False
2      Mona   35  Damascus   78.9     No    3  False
3  Ibraheem   20      Yafa   92.5    Yes    4   True
4     Malik   45     Irbid   88.0    Yes    5  False

In [73]:
df[df['Youth']]

       Name  Age   City  Score Passed  num  Youth
0      Emad   25  Amman   85.5    Yes    1   True
3  Ibraheem   20   Yafa   92.5    Yes    4   True

# More Examples about adding columns

In [74]:
# more on adding columns (features)

data = {'Name': ['Yafa', 'Karam', 'Batool'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)

df

     Name  Age
0    Yafa   25
1   Karam   30
2  Batool   35

In [75]:
df['Country'] = 'Jordan'
df

     Name  Age Country
0    Yafa   25  Jordan
1   Karam   30  Jordan
2  Batool   35  Jordan

In [76]:
# adding a column using a list
df['Score'] = [90, 85, None]     # df['Score'] = [90, 85, np.nan]

In [77]:
df

     Name  Age Country  Score
0    Yafa   25  Jordan   90.0
1   Karam   30  Jordan   85.0
2  Batool   35  Jordan    NaN

In [78]:
# Adding a column using a Series
df['Height'] = pd.Series([5.5, 6.0, 5.8])

In [79]:
df

     Name  Age Country  Score  Height
0    Yafa   25  Jordan   90.0     5.5
1   Karam   30  Jordan   85.0     6.0
2  Batool   35  Jordan    NaN     5.8

# Rename Columns

In [80]:
ddd = df.rename(columns = {'Height' : 'Height (in)'})
ddd

     Name  Age Country  Score  Height (in)
0    Yafa   25  Jordan   90.0          5.5
1   Karam   30  Jordan   85.0          6.0
2  Batool   35  Jordan    NaN          5.8

In [81]:
df

     Name  Age Country  Score  Height
0    Yafa   25  Jordan   90.0     5.5
1   Karam   30  Jordan   85.0     6.0
2  Batool   35  Jordan    NaN     5.8

In [82]:
df.rename(columns = {'Height' : 'Height (in)'}, inplace= True)

In [83]:
df

     Name  Age Country  Score  Height (in)
0    Yafa   25  Jordan   90.0          5.5
1   Karam   30  Jordan   85.0          6.0
2  Batool   35  Jordan    NaN          5.8

In [84]:
# creating a column using a mathematical operation
df['Height (in)'] = df['Height (in)'] * 30.48  # converting feet to cm
df.rename(columns = {'Height (in)' : 'Height (cm)'}, inplace= True)
df

     Name  Age Country  Score  Height (cm)
0    Yafa   25  Jordan   90.0      167.640
1   Karam   30  Jordan   85.0      182.880
2  Batool   35  Jordan    NaN      176.784

# Add column by conditions

In [85]:
df[df['Age'] > 30]

     Name  Age Country  Score  Height (cm)
2  Batool   35  Jordan    NaN      176.784

In [86]:
# using np.where to add a column based on a condition
df['Senior'] = np.where(df['Age'] > 30, 'Yes', 'No')
df

     Name  Age Country  Score  Height (cm) Senior
0    Yafa   25  Jordan   90.0      167.640     No
1   Karam   30  Jordan   85.0      182.880     No
2  Batool   35  Jordan    NaN      176.784    Yes

# Add column by multiple conditions

In [87]:
# Multiple Conditions

def age_category(age):

    if age >= 20 and age <= 25:
        return  'Yes'
    elif age >= 30 and age <= 34:
        return 'Maybe'
    else:
        return 'No'

df['Senior'] = df['Age'].apply(age_category)
df

     Name  Age Country  Score  Height (cm) Senior
0    Yafa   25  Jordan   90.0      167.640    Yes
1   Karam   30  Jordan   85.0      182.880  Maybe
2  Batool   35  Jordan    NaN      176.784     No

# Drop Columns

## Drop One Column

In [ ]:
# Drop one column
# employees = employees.drop(columns = 'Name')

In [92]:
employees = pd.DataFrame({
    'EmployeeID': [1, 2, 3, 4],
    'Name': ['Karam', 'Yafa', 'Batool', 'MOhammad'],
    'DeptID': [101, 102, 101, 103],
    'Salary': [400, 500, 380, 450],
    'Age': [30, 32, 23, 26],
    'Club': ['Football', 'Cooking', 'Sewing', 'Basketball']
})

In [93]:
employees

   EmployeeID      Name  DeptID  Salary  Age        Club
0           1     Karam     101     400   30    Football
1           2      Yafa     102     500   32     Cooking
2           3    Batool     101     380   23      Sewing
3           4  MOhammad     103     450   26  Basketball

In [94]:
employees.drop(columns = 'Club', inplace= True)
employees

   EmployeeID      Name  DeptID  Salary  Age
0           1     Karam     101     400   30
1           2      Yafa     102     500   32
2           3    Batool     101     380   23
3           4  MOhammad     103     450   26

In [ ]:
# Drop multiple columns

#Question: what's the difference between the 3 methods below?

employees.drop(columns=['Name', 'Age']) # Not inplace

employees = employees.drop(columns = ['Name',"Age"] ) # Inplace
employees

# employees.drop(columns = ['Name',"Age"] ,inplace = True) # Inplace
# employees

   EmployeeID  DeptID  Salary
0           1     101     400
1           2     102     500
2           3     101     380
3           4     103     450

In [96]:
employees

   EmployeeID  DeptID  Salary
0           1     101     400
1           2     102     500
2           3     101     380
3           4     103     450

# Appending new rows using (concat)

In [2]:
import pandas as pd

In [3]:
employees = pd.DataFrame({'EmployeeID': [1, 2, 3, 4],
                          'Name': ['Karam', 'yafa', 'Husam', 'Mohammad'],
                          'DeptID': [101, 102, 101, 103]})

In [4]:
employees.shape

(4, 3)

In [5]:
employees

   EmployeeID      Name  DeptID
0           1     Karam     101
1           2      yafa     102
2           3     Husam     101
3           4  Mohammad     103

In [6]:
# rows to append to data frame one
rows = pd.DataFrame({'EmployeeID': [5,20], 'Name': ['Ammar',"Omar"], 'DeptID': [102,105]})

In [7]:
rows

   EmployeeID   Name  DeptID
0           5  Ammar     102
1          20   Omar     105

In [8]:
employees_concatenated = pd.concat([rows,employees], axis = 0)

In [9]:
employees_concatenated

   EmployeeID      Name  DeptID
0           5     Ammar     102
1          20      Omar     105
0           1     Karam     101
1           2      yafa     102
2           3     Husam     101
3           4  Mohammad     103

#Task 4:

Add 3 more rows into the previous df.

In [21]:
rows = pd.DataFrame({'EmployeeID': [6,7,8], 'Name': ['Ameen',"Ahmad","Ali"], 'DeptID': [102,105,103]})
employees_concatenated_2 = pd.concat([employees_concatenated, rows], axis=0, ignore_index=True)
employees_concatenated_2

   EmployeeID      Name  DeptID
0           5     Ammar     102
1          20      Omar     105
2           1     Karam     101
3           2      yafa     102
4           3     Husam     101
5           4  Mohammad     103
6           6     Ameen     102
7           7     Ahmad     105
8           8       Ali     103

# Drop Rows

In [12]:
employees

   EmployeeID      Name  DeptID
0           1     Karam     101
1           2      yafa     102
2           3     Husam     101
3           4  Mohammad     103

In [13]:
employees.drop(index = [0,1] )

   EmployeeID      Name  DeptID
2           3     Husam     101
3           4  Mohammad     103

In [14]:
employees

   EmployeeID      Name  DeptID
0           1     Karam     101
1           2      yafa     102
2           3     Husam     101
3           4  Mohammad     103

In [15]:
employees = employees.drop(index = [0,1])
employees

   EmployeeID      Name  DeptID
2           3     Husam     101
3           4  Mohammad     103

In [ ]:
#Or using this:

# employees.drop(index = [0,1] , inplace = True)
# employees

## Dropping Using Condition

In [16]:
rows_to_drop = employees[employees['Name'] == "Husam"].index
rows_to_drop

Index([2], dtype='int64')

In [17]:
employees['Name'] == "Husam"

2     True
3    False
Name: Name, dtype: bool

In [18]:
employees.drop(index = rows_to_drop)

   EmployeeID      Name  DeptID
3           4  Mohammad     103

# Quick Reviews

In [32]:
data = [
    {'Product': 'Laptop', 'Price': 1200, 'Quantity': 5, 'Discount': 10},
    {'Product': 'Tablet', 'Price': 600, 'Quantity': 10, 'Discount': 15},
    {'Product': 'Smartphone', 'Price': 800, 'Quantity': 7, 'Discount': 5},
    {'Product': 'Monitor', 'Price': 300, 'Quantity': 12, 'Discount': 20}
]

df = pd.DataFrame(data)

df

      Product  Price  Quantity  Discount
0      Laptop   1200         5        10
1      Tablet    600        10        15
2  Smartphone    800         7         5
3     Monitor    300        12        20

In [33]:
import numpy as np

In [34]:
# use  np.where to add a new column high_price that marks products as "Yes" if the
# Price is greater than 700, and "No" otherwise.
df['High_Price'] = np.where(df['Price'] > 700 ,'Yes' , 'No')
df

      Product  Price  Quantity  Discount High_Price
0      Laptop   1200         5        10        Yes
1      Tablet    600        10        15         No
2  Smartphone    800         7         5        Yes
3     Monitor    300        12        20         No

In [38]:
row = pd.DataFrame([{'Product': 'Mouse', 'Price': 50, 'Quantity': 3, 'Discount': 10, 'High_Price': 'No'}])
df = pd.concat([df, row], axis=0, ignore_index=True)

In [39]:
# define a function that  categorizes products named category based on Quantity, 'high'
# if quantity is greater than 10 , 'medium' if quantity > 5  else : 'low stock'

def categorizes(Quantity):
  if Quantity >= 10:
        return  'high'
  elif Quantity >= 5:
        return 'medium'
  else:
        return 'low'

df['Stock'] = df['Quantity'].apply(categorizes)
df

      Product  Price  Quantity  Discount High_Price   Stock
0      Laptop   1200         5        10        Yes  medium
1      Tablet    600        10        15         No    high
2  Smartphone    800         7         5        Yes  medium
3     Monitor    300        12        20         No    high
4       Mouse     50         3        10         No     low

In [40]:
data = pd.DataFrame({
    'A': [1, 6, 3, 4, 5],
    'B': [5, 4, 3, 5, 1]
})

data

   A  B
0  1  5
1  6  4
2  3  3
3  4  5
4  5  1

In [41]:
# using np.where with two conditions from different columns
data["Result"] = np.where(
    (data["A"] > 2) & (data["B"] < 4), "Condition Met", "Condition Not Met"
)

data

   A  B             Result
0  1  5  Condition Not Met
1  6  4  Condition Not Met
2  3  3      Condition Met
3  4  5  Condition Not Met
4  5  1      Condition Met

# Great Job ❤