# Missing Data

Let's show a few convenient methods to deal with Missing Data in pandas:

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'A':[1,2,np.nan, 4, np.nan, 7, 3],
                  'B':[5,np.nan,np.nan, 8, 9, np.nan, 10],
                  'C':[1,2,3, 4, 5, 6, 7]})

In [3]:
df

     A     B  C
0  1.0   5.0  1
1  2.0   NaN  2
2  NaN   NaN  3
3  4.0   8.0  4
4  NaN   9.0  5
5  7.0   NaN  6
6  3.0  10.0  7

In [6]:
df.isna().sum()

A    2
B    3
C    0
dtype: int64

In [7]:
df.dropna()

     A     B  C
0  1.0   5.0  1
3  4.0   8.0  4
6  3.0  10.0  7

In [8]:
df.dropna(axis=1)

   C
0  1
1  2
2  3
3  4
4  5
5  6
6  7

In [18]:
df.dropna(thresh=2)  #Keep any row that has at least 2 non-NaN values

     A     B  C
0  1.0   5.0  1
1  2.0   NaN  2
3  4.0   8.0  4
4  NaN   9.0  5
5  7.0   NaN  6
6  3.0  10.0  7

In [19]:
df.fillna(value='Missing')

         A        B  C
0      1.0      5.0  1
1      2.0  Missing  2
2  Missing  Missing  3
3      4.0      8.0  4
4  Missing      9.0  5
5      7.0  Missing  6
6      3.0     10.0  7

In [20]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    3.4
3    4.0
4    3.4
5    7.0
6    3.0
Name: A, dtype: float64

In [23]:
df.fillna(method='ffill', limit=2) # what if limit was 2? (2 consecutive NaNs will be filled)

C:\Users\DELL\AppData\Local\Temp\ipykernel_2696\3777101666.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=2) # what if limit was 2? (2 consecutive NaNs will be filled)

     A     B  C
0  1.0   5.0  1
1  2.0   5.0  2
2  2.0   5.0  3
3  4.0   8.0  4
4  4.0   9.0  5
5  7.0   9.0  6
6  3.0  10.0  7

In [24]:
df.fillna(method='bfill', limit=1)

C:\Users\DELL\AppData\Local\Temp\ipykernel_2696\3785261496.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', limit=1)

     A     B  C
0  1.0   5.0  1
1  2.0   NaN  2
2  4.0   8.0  3
3  4.0   8.0  4
4  7.0   9.0  5
5  7.0  10.0  6
6  3.0  10.0  7

In [25]:
df # for comparison

     A     B  C
0  1.0   5.0  1
1  2.0   NaN  2
2  NaN   NaN  3
3  4.0   8.0  4
4  NaN   9.0  5
5  7.0   NaN  6
6  3.0  10.0  7

In [26]:
df.interpolate()

     A     B  C
0  1.0   5.0  1
1  2.0   6.0  2
2  3.0   7.0  3
3  4.0   8.0  4
4  5.5   9.0  5
5  7.0   9.5  6
6  3.0  10.0  7

# Task 1:

Using the following DataFrame:
```
data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    'Sales_A': [1000, np.nan, 1200, np.nan, 1600, 1700],
    'Sales_B': [900, 950, np.nan, np.nan, 1100, 1150],
    'Remarks': ['OK', np.nan, 'OK', 'Late', np.nan, 'OK']
}
```
perform the following operations:


1.  Drop all rows that have all values missing. (you can use a quick Google Search in here!)
2.  Drop all rows that have less than 2 non-missing values.
3.  Fill missing values in Remarks with 'No Info'.
4.  Fill missing values in Sales_A with the mean of that column.
5.  Use forward fill to fill only 1 missing value in Sales_B.
6.  Use interpolation to fill remaining missing values in Sales_B.

In [41]:
data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',np.nan],
    'Sales_A': [1000, np.nan, 1200, np.nan, 1600, 1700,np.nan],
    'Sales_B': [900, 950, np.nan, np.nan, 1100, 1150,np.nan],
    'Remarks': ['OK', np.nan, 'OK', 'Late', np.nan, 'OK',np.nan]
}

df = pd.DataFrame(data)
df

  Month  Sales_A  Sales_B Remarks
0   Jan   1000.0    900.0      OK
1   Feb      NaN    950.0     NaN
2   Mar   1200.0      NaN      OK
3   Apr      NaN      NaN    Late
4   May   1600.0   1100.0     NaN
5   Jun   1700.0   1150.0      OK
6   NaN      NaN      NaN     NaN

In [42]:
# Step 1: Drop rows where all values are missing (just in case)
df = df.dropna(how='all')
df

  Month  Sales_A  Sales_B Remarks
0   Jan   1000.0    900.0      OK
1   Feb      NaN    950.0     NaN
2   Mar   1200.0      NaN      OK
3   Apr      NaN      NaN    Late
4   May   1600.0   1100.0     NaN
5   Jun   1700.0   1150.0      OK

In [43]:
# Step 2: Drop rows with fewer than 2 non-null values
df = df.dropna(thresh=2)
df

  Month  Sales_A  Sales_B Remarks
0   Jan   1000.0    900.0      OK
1   Feb      NaN    950.0     NaN
2   Mar   1200.0      NaN      OK
3   Apr      NaN      NaN    Late
4   May   1600.0   1100.0     NaN
5   Jun   1700.0   1150.0      OK

In [45]:
# Step 3: Fill missing values in 'Remarks' with 'No Info'
df['Remarks'] = df['Remarks'].fillna('No Info')
df

  Month  Sales_A  Sales_B  Remarks
0   Jan   1000.0    900.0       OK
1   Feb      NaN    950.0  No Info
2   Mar   1200.0      NaN       OK
3   Apr      NaN      NaN     Late
4   May   1600.0   1100.0  No Info
5   Jun   1700.0   1150.0       OK

In [46]:
# Step 4: Fill missing values in 'Sales_A' with the column's mean
df['Sales_A'] = df['Sales_A'].fillna(df['Sales_A'].mean())
df

  Month  Sales_A  Sales_B  Remarks
0   Jan   1000.0    900.0       OK
1   Feb   1375.0    950.0  No Info
2   Mar   1200.0      NaN       OK
3   Apr   1375.0      NaN     Late
4   May   1600.0   1100.0  No Info
5   Jun   1700.0   1150.0       OK

In [47]:
# Step 5: Forward fill one missing value only in 'Sales_B'
df['Sales_B'] = df['Sales_B'].fillna(method='ffill', limit=1)
df

C:\Users\DELL\AppData\Local\Temp\ipykernel_2696\12176672.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Sales_B'] = df['Sales_B'].fillna(method='ffill', limit=1)

  Month  Sales_A  Sales_B  Remarks
0   Jan   1000.0    900.0       OK
1   Feb   1375.0    950.0  No Info
2   Mar   1200.0    950.0       OK
3   Apr   1375.0      NaN     Late
4   May   1600.0   1100.0  No Info
5   Jun   1700.0   1150.0       OK

In [48]:
# Step 6: Interpolate remaining missing values in 'Sales_B'
df['Sales_B'] = df['Sales_B'].interpolate()
df

  Month  Sales_A  Sales_B  Remarks
0   Jan   1000.0    900.0       OK
1   Feb   1375.0    950.0  No Info
2   Mar   1200.0    950.0       OK
3   Apr   1375.0   1025.0     Late
4   May   1600.0   1100.0  No Info
5   Jun   1700.0   1150.0       OK

# Great Job!