# Pandas (Sorting, Cleaning and Casting data)

This Notebook includes the following contents:

* Sorting Data (ascending or descending).
* Cleaning Data.
* Casting Data.

# SORTING

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Name': ['Yafa', 'Karam', 'Emad', 'Zain'],
    'Age': [22, 30, 35, 22],
    'Salary': [60000,50000, 70000, 55000]
}

df = pd.DataFrame(data)

df

    Name  Age  Salary
0   Yafa   22   60000
1  Karam   30   50000
2   Emad   35   70000
3   Zain   22   55000

In [3]:
# Sort by 'Age'---> by default it sorts in ascending order (تصاعدي)
df_sorted = df.sort_values(by='Age')
df_sorted

    Name  Age  Salary
0   Yafa   22   60000
3   Zain   22   55000
1  Karam   30   50000
2   Emad   35   70000

In [4]:
# Sort by Age and then by Salary (if two people have the same age, this sorts them by their salary)
df_sorted_multi = df.sort_values(by=['Age', 'Salary'])
df_sorted_multi

    Name  Age  Salary
3   Zain   22   55000
0   Yafa   22   60000
1  Karam   30   50000
2   Emad   35   70000

In [5]:
# sort by salary in descending order

df_sorted_desc = df.sort_values(by='Salary', ascending=False)
df_sorted_desc

    Name  Age  Salary
2   Emad   35   70000
0   Yafa   22   60000
3   Zain   22   55000
1  Karam   30   50000

In [6]:
df_sorted_desc = df.sort_values(by=['Salary', "Age"], ascending=False) # Why is Karam's record last?
df_sorted_desc

    Name  Age  Salary
2   Emad   35   70000
0   Yafa   22   60000
3   Zain   22   55000
1  Karam   30   50000

In [7]:
# real world Examples

"""
sorting the sales data helps identify the most popular products,
which can help make inventory decisions,
example : if headphones are the top-selling product, you might want to buy more of them
"""
sales_data = {
    'Product': ['Laptop', 'Headphones', 'Keyboard', 'Mouse'],
    'Units Sold': [150, 300, 200, 250],
    'Date': pd.to_datetime(['2024-01-15', '2024-01-10', '2024-01-12', '2024-01-14'])
}

sales_df = pd.DataFrame(sales_data)

In [8]:
sales_df

      Product  Units Sold       Date
0      Laptop         150 2024-01-15
1  Headphones         300 2024-01-10
2    Keyboard         200 2024-01-12
3       Mouse         250 2024-01-14

# Task 1:
Sort by Units Sold in descending order to find top-selling products.

Then, change the index so that it starts from the highest selling to the lowest selling product.

In [9]:
top_selling = sales_df.sort_values(by='Units Sold', ascending=False)
top_selling

      Product  Units Sold       Date
1  Headphones         300 2024-01-10
3       Mouse         250 2024-01-14
2    Keyboard         200 2024-01-12
0      Laptop         150 2024-01-15

In [10]:
top_selling.reset_index(drop = True)

      Product  Units Sold       Date
0  Headphones         300 2024-01-10
1       Mouse         250 2024-01-14
2    Keyboard         200 2024-01-12
3      Laptop         150 2024-01-15

# Task 2:

Given this  data:
```
data = {
    'Name': ['Yafa', 'Karam', 'Emad', 'Zain',"Emad","Karam"],
    'Age': [25, 30, 25, 22, 30,22],
    'Grade': [88, 75, 92, 85, 90,86]
}
```
Sort by age in ascending order and grade in descending order

In [12]:
data = {
    'Name': ['Yafa', 'Karam', 'Emad', 'Zain',"Emad","Karam"],
    'Age': [25, 30, 25, 22, 30,22],
    'Grade': [88, 75, 92, 85, 90,86]
}

df = pd.DataFrame(data)

df_sorted = df.sort_values(by=['Age', 'Grade'], ascending=[True, False])
df_sorted.reset_index(drop = True)

    Name  Age  Grade
0  Karam   22     86
1   Zain   22     85
2   Emad   25     92
3   Yafa   25     88
4   Emad   30     90
5  Karam   30     75

# Cleaning

In [13]:
data = {
    'first': ['Mohammad', 'Abed', 'Omar', 'Emad', np.nan, None, 'NA'],
    'last': ['abu labun', 'battekh', 'shommam', 'khayyat', np.nan, np.nan, 'Missing'],
    'email': ['Mohammad@gmail.com', 'Abed@email.com', 'Omar@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

df = pd.DataFrame(data)

**Dealing with Actual missing values**

In [14]:
df  # Notice anything about the missing data values here?

      first       last                email      age
0  Mohammad  abu labun   Mohammad@gmail.com       33
1      Abed    battekh       Abed@email.com       55
2      Omar    shommam       Omar@email.com       63
3      Emad    khayyat                 None       36
4       NaN        NaN                  NaN     None
5      None        NaN  Anonymous@email.com     None
6        NA    Missing                   NA  Missing

In [15]:
df.isnull()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6  False  False  False  False

In [17]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6  False  False  False  False

In [19]:
df.isna().sum()

first    2
last     2
email    2
age      2
dtype: int64

In [20]:
# Drop Missing Values (it removes None, np.nan)
df.dropna(axis = "index", how = "any" )  # index means i need to drop rows and any will drop rows if any value of that row is missing

      first       last               email      age
0  Mohammad  abu labun  Mohammad@gmail.com       33
1      Abed    battekh      Abed@email.com       55
2      Omar    shommam      Omar@email.com       63
6        NA    Missing                  NA  Missing

In [21]:
df.dropna(axis = "index", how = "all")

      first       last                email      age
0  Mohammad  abu labun   Mohammad@gmail.com       33
1      Abed    battekh       Abed@email.com       55
2      Omar    shommam       Omar@email.com       63
3      Emad    khayyat                 None       36
5      None        NaN  Anonymous@email.com     None
6        NA    Missing                   NA  Missing

In [22]:
df.dropna(axis = "columns", how = "all")

      first       last                email      age
0  Mohammad  abu labun   Mohammad@gmail.com       33
1      Abed    battekh       Abed@email.com       55
2      Omar    shommam       Omar@email.com       63
3      Emad    khayyat                 None       36
4       NaN        NaN                  NaN     None
5      None        NaN  Anonymous@email.com     None
6        NA    Missing                   NA  Missing

In [23]:
df.dropna(axis = "columns", how = "any") # Which values will remain?

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [24]:
# dropping na based on a specific column
df.dropna(axis = "index", subset = ["email"]) # how parameter is not needed in this case since it's one column

      first       last                email      age
0  Mohammad  abu labun   Mohammad@gmail.com       33
1      Abed    battekh       Abed@email.com       55
2      Omar    shommam       Omar@email.com       63
5      None        NaN  Anonymous@email.com     None
6        NA    Missing                   NA  Missing

In [25]:
# in case of multiples columns
df.dropna(axis = 'index', how = "any", subset = ["email","last"])

      first       last               email      age
0  Mohammad  abu labun  Mohammad@gmail.com       33
1      Abed    battekh      Abed@email.com       55
2      Omar    shommam      Omar@email.com       63
6        NA    Missing                  NA  Missing

In [26]:
df

      first       last                email      age
0  Mohammad  abu labun   Mohammad@gmail.com       33
1      Abed    battekh       Abed@email.com       55
2      Omar    shommam       Omar@email.com       63
3      Emad    khayyat                 None       36
4       NaN        NaN                  NaN     None
5      None        NaN  Anonymous@email.com     None
6        NA    Missing                   NA  Missing

In [27]:
df.dropna(axis = 'index', how = "all", subset = ["email","last"])  # What's wrong with this line?

      first       last                email      age
0  Mohammad  abu labun   Mohammad@gmail.com       33
1      Abed    battekh       Abed@email.com       55
2      Omar    shommam       Omar@email.com       63
3      Emad    khayyat                 None       36
5      None        NaN  Anonymous@email.com     None
6        NA    Missing                   NA  Missing

**Dealing with none actual missing data**

In [28]:
data = {
    'first': ['Mohammad', 'Abed', 'Omar', 'Emad', np.nan, None, 'NA'],
    'last': ['abu labun', 'battekh', 'shommam', 'khayyat', np.nan, np.nan, 'Missing'],
    'email': ['Mohammad@gmail.com', 'Abed@email.com', 'Omar@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}
df = pd.DataFrame(data)

In [29]:
df

      first       last                email      age
0  Mohammad  abu labun   Mohammad@gmail.com       33
1      Abed    battekh       Abed@email.com       55
2      Omar    shommam       Omar@email.com       63
3      Emad    khayyat                 None       36
4       NaN        NaN                  NaN     None
5      None        NaN  Anonymous@email.com     None
6        NA    Missing                   NA  Missing

In [34]:
df.isna().sum()

first    2
last     2
email    2
age      2
dtype: int64

In [35]:
# Let's replace non actual missing values with actual missing values

# df.replace("Missing" , np.nan, inplace = True)
# df.replace("NA" , np.nan, inplace = True)

# or

df = df.replace({"Missing":np.nan , "NA":np.nan})

In [36]:
df

      first       last                email   age
0  Mohammad  abu labun   Mohammad@gmail.com    33
1      Abed    battekh       Abed@email.com    55
2      Omar    shommam       Omar@email.com    63
3      Emad    khayyat                 None    36
4       NaN        NaN                  NaN  None
5      None        NaN  Anonymous@email.com  None
6       NaN        NaN                  NaN   NaN

In [37]:
df.isna().sum()

first    3
last     3
email    3
age      3
dtype: int64

In [38]:
# fillna values
df.fillna("Missing") # you can use any value you want

      first       last                email      age
0  Mohammad  abu labun   Mohammad@gmail.com       33
1      Abed    battekh       Abed@email.com       55
2      Omar    shommam       Omar@email.com       63
3      Emad    khayyat              Missing       36
4   Missing    Missing              Missing  Missing
5   Missing    Missing  Anonymous@email.com  Missing
6   Missing    Missing              Missing  Missing

# Casting

In [39]:
data = {
    'first': ['Mohammad', 'Abed', 'Omar', 'Emad', np.nan, None, 'NA'],
    'last': ['abu labun', 'battekh', 'shommam', 'khayyat', np.nan, np.nan, 'Missing'],
    'email': ['Mohammad@gmail.com', 'Abed@email.com', 'Omar@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}
df = pd.DataFrame(data)

In [40]:
df = df.replace({"Missing":np.nan , "NA":np.nan})

In [41]:
df

      first       last                email   age
0  Mohammad  abu labun   Mohammad@gmail.com    33
1      Abed    battekh       Abed@email.com    55
2      Omar    shommam       Omar@email.com    63
3      Emad    khayyat                 None    36
4       NaN        NaN                  NaN  None
5      None        NaN  Anonymous@email.com  None
6       NaN        NaN                  NaN   NaN

In [ ]:
# common ways of filling missing values
df['age'].fillna(df['age'].mean())         # Why did we get an error here?

TypeError: can only concatenate str (not "int") to str

In [43]:
# check data type of each column
df.dtypes

first    object
last     object
email    object
age      object
dtype: object

In [44]:
type(np.nan)

float

In [45]:
# age column is object (it's just like string)---> let's fix the issue

df['age'] = df['age'].astype(float)
df

      first       last                email   age
0  Mohammad  abu labun   Mohammad@gmail.com  33.0
1      Abed    battekh       Abed@email.com  55.0
2      Omar    shommam       Omar@email.com  63.0
3      Emad    khayyat                 None  36.0
4       NaN        NaN                  NaN   NaN
5      None        NaN  Anonymous@email.com   NaN
6       NaN        NaN                  NaN   NaN

In [46]:
df.dtypes

first     object
last      object
email     object
age      float64
dtype: object

In [47]:
df['age'] = df['age'].fillna(df['age'].mean())
df

      first       last                email    age
0  Mohammad  abu labun   Mohammad@gmail.com  33.00
1      Abed    battekh       Abed@email.com  55.00
2      Omar    shommam       Omar@email.com  63.00
3      Emad    khayyat                 None  36.00
4       NaN        NaN                  NaN  46.75
5      None        NaN  Anonymous@email.com  46.75
6       NaN        NaN                  NaN  46.75

# Task 3:
Given the following data:
```
data = {
    'Name': ['Salma', 'Ali', 'Nada', 'Tariq', 'Lina'],
    'Age': ['25', '32', None, '27', '29'],
    'Satisfaction': ['4.5', '3.8', None, '5.0', '3.0']
}
```
Perform the following:
1. Display the DataFrame to see what you’re working with.

2. Convert 'Age' and 'Satisfaction' to float using .astype(float).

3. Fill missing Age values with the mean Age.

4. Fill missing values in the 'Satisfaction' column with a fixed value: 3.0.

5. Print the cleaned DataFrame with correct types and filled values.

In [48]:
data = {
    'Name': ['Salma', 'Ali', 'Nada', 'Tariq', 'Lina'],
    'Age': ['25', '32', None, '27', '29'],
    'Satisfaction': ['4.5', '3.8', None, '5.0', '3.0']
}

df = pd.DataFrame(data)

# Before cleaning
print("Before cleaning:")
print(df)
print("\nData types:\n", df.dtypes)
print("\nMissing values:\n", df.isna().sum())

Before cleaning:
    Name   Age Satisfaction
0  Salma    25          4.5
1    Ali    32          3.8
2   Nada  None         None
3  Tariq    27          5.0
4   Lina    29          3.0

Data types:
 Name            object
Age             object
Satisfaction    object
dtype: object

Missing values:
 Name            0
Age             1
Satisfaction    1
dtype: int64

In [50]:
# Step 2: Convert to numeric
# Convert to float
df['Age'] = df['Age'].astype(float)
df['Satisfaction'] = df['Satisfaction'].astype(float)
print(df.dtypes)
df

Name             object
Age             float64
Satisfaction    float64
dtype: object

    Name   Age  Satisfaction
0  Salma  25.0           4.5
1    Ali  32.0           3.8
2   Nada   NaN           NaN
3  Tariq  27.0           5.0
4   Lina  29.0           3.0

In [51]:
# Step 3: Fill missing Age with mean
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

    Name    Age  Satisfaction
0  Salma  25.00           4.5
1    Ali  32.00           3.8
2   Nada  28.25           NaN
3  Tariq  27.00           5.0
4   Lina  29.00           3.0

In [52]:
# Step 4: Fill Satisfaction with 3.0
df['Satisfaction'] = df['Satisfaction'].fillna(3.0)
df

    Name    Age  Satisfaction
0  Salma  25.00           4.5
1    Ali  32.00           3.8
2   Nada  28.25           3.0
3  Tariq  27.00           5.0
4   Lina  29.00           3.0

In [53]:
# Final cleaned DataFrame
print("\nAfter cleaning:")
print(df)
print("\nData types:\n", df.dtypes)

After cleaning:
    Name    Age  Satisfaction
0  Salma  25.00           4.5
1    Ali  32.00           3.8
2   Nada  28.25           3.0
3  Tariq  27.00           5.0
4   Lina  29.00           3.0

Data types:
 Name             object
Age             float64
Satisfaction    float64
dtype: object

# Great Job ❤