___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# Data Input and Output

This notebook is the reference code for getting input and output, pandas can read a variety of file types using its pd.read_ methods. Let's take a look at the most common data types:

In [1]:
import numpy as np
import pandas as pd

## CSV

### CSV Input

In [2]:
df = pd.read_csv('test.csv', encoding='windows-1256') 
df

,التسلسل,اسم الجمعية,الرقم الوطني,نوع الجمعية,عدد الأعضاء,المحافظة
0,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,الجمعية التعاونية لمستخدمي المياه حوض (5) الزر...,5.201131e+08,زراعيه,81.0,اربد
2,2.0,جمعية مستخدمي المياه مضخه (14) التعاونية الزراعية,5.201130e+08,زراعية,135.0,اربد
3,3.0,جمعية الباقورة لمستخدمي المياه حوض (3+4) التعا...,5.201131e+08,زراعيه,90.0,اربد
4,4.0,جمعية عين السليخات التعاونية الزراعية,5.200727e+08,زراعية,46.0,اربد
...,...,...,...,...,...,...
1454,1454.0,جمعية السيق البارد التعاونية السياحية م.غ,1.120224e+09,سياحية,15.0,معان
1455,1455.0,جمعية ابناء اذرح السياحية التعاونية,1.120224e+09,سياحية,21.0,معان
1456,1456.0,جمعية جبل مسعوده التعاونية السياحية,1.120224e+09,سياحية,45.0,معان
1457,1457.0,جمعية الجلف التعاونية السياحية م.غ,1.120234e+09,سياحية,15.0,معان
1458,1458.0,جمعية الطيبة الجنوبية السياحية م.غ,1.120234e+09,سياحية,141.0,معان

In [3]:
df = df.drop(index=0).reset_index()
df

,index,التسلسل,اسم الجمعية,الرقم الوطني,نوع الجمعية,عدد الأعضاء,المحافظة
0,1,1.0,الجمعية التعاونية لمستخدمي المياه حوض (5) الزر...,5.201131e+08,زراعيه,81.0,اربد
1,2,2.0,جمعية مستخدمي المياه مضخه (14) التعاونية الزراعية,5.201130e+08,زراعية,135.0,اربد
2,3,3.0,جمعية الباقورة لمستخدمي المياه حوض (3+4) التعا...,5.201131e+08,زراعيه,90.0,اربد
3,4,4.0,جمعية عين السليخات التعاونية الزراعية,5.200727e+08,زراعية,46.0,اربد
4,5,5.0,جمعية مزارعي طبقة فحل التعاونية الزراعية المضخ...,5.200626e+08,زراعية,88.0,اربد
...,...,...,...,...,...,...,...
1453,1454,1454.0,جمعية السيق البارد التعاونية السياحية م.غ,1.120224e+09,سياحية,15.0,معان
1454,1455,1455.0,جمعية ابناء اذرح السياحية التعاونية,1.120224e+09,سياحية,21.0,معان
1455,1456,1456.0,جمعية جبل مسعوده التعاونية السياحية,1.120224e+09,سياحية,45.0,معان
1456,1457,1457.0,جمعية الجلف التعاونية السياحية م.غ,1.120234e+09,سياحية,15.0,معان
1457,1458,1458.0,جمعية الطيبة الجنوبية السياحية م.غ,1.120234e+09,سياحية,141.0,معان

In [4]:
df.isnull().sum()

index            0
التسلسل          0
اسم الجمعية      0
الرقم الوطني     0
نوع الجمعية      0
عدد الأعضاء      1
المحافظة         0
dtype: int64

In [5]:
df[df['عدد الأعضاء'].isnull()]

,index,التسلسل,اسم الجمعية,الرقم الوطني,نوع الجمعية,عدد الأعضاء,المحافظة
884,885,885.0,جمعية الشهد التعاونية,820072745.0,سياحية,NaN,عجلون

In [6]:
df.drop(columns=['index'], inplace=True)
df

,التسلسل,اسم الجمعية,الرقم الوطني,نوع الجمعية,عدد الأعضاء,المحافظة
0,1.0,الجمعية التعاونية لمستخدمي المياه حوض (5) الزر...,5.201131e+08,زراعيه,81.0,اربد
1,2.0,جمعية مستخدمي المياه مضخه (14) التعاونية الزراعية,5.201130e+08,زراعية,135.0,اربد
2,3.0,جمعية الباقورة لمستخدمي المياه حوض (3+4) التعا...,5.201131e+08,زراعيه,90.0,اربد
3,4.0,جمعية عين السليخات التعاونية الزراعية,5.200727e+08,زراعية,46.0,اربد
4,5.0,جمعية مزارعي طبقة فحل التعاونية الزراعية المضخ...,5.200626e+08,زراعية,88.0,اربد
...,...,...,...,...,...,...
1453,1454.0,جمعية السيق البارد التعاونية السياحية م.غ,1.120224e+09,سياحية,15.0,معان
1454,1455.0,جمعية ابناء اذرح السياحية التعاونية,1.120224e+09,سياحية,21.0,معان
1455,1456.0,جمعية جبل مسعوده التعاونية السياحية,1.120224e+09,سياحية,45.0,معان
1456,1457.0,جمعية الجلف التعاونية السياحية م.غ,1.120234e+09,سياحية,15.0,معان
1457,1458.0,جمعية الطيبة الجنوبية السياحية م.غ,1.120234e+09,سياحية,141.0,معان

In [8]:
df['التسلسل'].astype(int)
df

,التسلسل,اسم الجمعية,الرقم الوطني,نوع الجمعية,عدد الأعضاء,المحافظة
0,1.0,الجمعية التعاونية لمستخدمي المياه حوض (5) الزر...,5.201131e+08,زراعيه,81.0,اربد
1,2.0,جمعية مستخدمي المياه مضخه (14) التعاونية الزراعية,5.201130e+08,زراعية,135.0,اربد
2,3.0,جمعية الباقورة لمستخدمي المياه حوض (3+4) التعا...,5.201131e+08,زراعيه,90.0,اربد
3,4.0,جمعية عين السليخات التعاونية الزراعية,5.200727e+08,زراعية,46.0,اربد
4,5.0,جمعية مزارعي طبقة فحل التعاونية الزراعية المضخ...,5.200626e+08,زراعية,88.0,اربد
...,...,...,...,...,...,...
1453,1454.0,جمعية السيق البارد التعاونية السياحية م.غ,1.120224e+09,سياحية,15.0,معان
1454,1455.0,جمعية ابناء اذرح السياحية التعاونية,1.120224e+09,سياحية,21.0,معان
1455,1456.0,جمعية جبل مسعوده التعاونية السياحية,1.120224e+09,سياحية,45.0,معان
1456,1457.0,جمعية الجلف التعاونية السياحية م.غ,1.120234e+09,سياحية,15.0,معان
1457,1458.0,جمعية الطيبة الجنوبية السياحية م.غ,1.120234e+09,سياحية,141.0,معان

In [9]:
df.drop(index=884, inplace=True)

In [10]:
df.isnull().sum()

التسلسل          0
اسم الجمعية      0
الرقم الوطني     0
نوع الجمعية      0
عدد الأعضاء      0
المحافظة         0
dtype: int64

In [11]:
df['عدد الأعضاء'].mean()

np.float64(88.36582017844887)

### CSV Output

In [13]:
df.to_csv('test-fixed.csv', encoding='utf-8')

## Excel
Pandas can read and write excel files, keep in mind, this only imports data. Not formulas or images, having images or macros may cause this read_excel method to crash.

### Excel Input

In [15]:
excel_df = pd.read_excel('جداول_القطاع_العام_الكلي_2015.xlsx', sheet_name='توزريع العاملين')

In [16]:
excel_df

,توزيع العاملين في نهاية السنة حسب الجنسية والصنف لسنة 2015,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,اصناف العاملين,العراقيون,العرب,المجموع,NaN,NaN,
1,رئيس الشركة والمدراء العامون ومعاونيهم,18,0,18,NaN,NaN,NaN
2,العاملون في الامور الادارية والذاتية والاحصاء ...,9558,6,9564,NaN,NaN,NaN
3,العاملون في الحسابات والتدقيق,3561,4,3565,NaN,NaN,NaN
4,العاملون في المشتريات والاستيرادات,975,2,977,NaN,NaN,NaN
5,العاملون في المبيــعات,10055,4,10059,NaN,NaN,NaN
6,العاملون في المخــازن,3601,5,3606,NaN,NaN,NaN
7,العاملون في الشعب الفنيــــة,6302,4,6306,NaN,NaN,NaN
8,العاملون في شعبة الصيانة والتصليح والانتاج,8311,6,8317,NaN,NaN,NaN
9,العاملون في الخـدمــات,6204,5,6209,NaN,NaN,NaN
10,المجموع,48585,36,48621,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,توزيع العاملين في نهاية السنة حسب الجنس والصن...,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,اصناف العاملين,ذكور,اناث,المجموع,NaN,NaN,NaN
15,رئيس الشركة والمدراء العامون ومعاونيهم,18,0,18,NaN,NaN,NaN
16,العاملون في الامور الادارية والذاتية والاحصاء ...,6249,3315,9564,NaN,NaN,NaN
17,العاملون في الحسابات والتدقيق,2070,1495,3565,NaN,NaN,NaN
18,العاملون في المشتريات والاستيرادات,610,367,977,NaN,NaN,NaN
19,العاملون في المبيــعات,7968,2091,10059,NaN,NaN,NaN
20,العاملون في المخــازن,2534,1072,3606,NaN,NaN,NaN
21,العاملون في الشعب الفنيــــة,4871,1435,6306,NaN,NaN,NaN
22,العاملون في شعبة الصيانة والتصليح والانتاج,7347,970,8317,NaN,NaN,NaN
23,العاملون في الخـدمــات,5598,611,6209,NaN,NaN,NaN
24,المجموع,37265,11356,48621,NaN,NaN,NaN

In [19]:
excel_df.drop(columns=['Unnamed: 4','Unnamed: 5','Unnamed: 6'], inplace=True)

In [23]:
excel_df.rename(
    columns={
        "2015 توزيع العاملين في نهاية السنة حسب الجنسية والصنف لسنة ": "اصناف العاملين",
        "Unnamed: 1": "العراقيون",
        "Unnamed: 2": "العرب",
        "Unnamed: 3": "المجموع",
    },
    inplace=True,
)

In [24]:
excel_df.drop(index=0, inplace=True)

In [25]:
excel_df.dropna(how='all', inplace=True)

In [27]:
excel_df

,توزيع العاملين في نهاية السنة حسب الجنسية والصنف لسنة 2015,العراقيون,العرب,المجموع
1,رئيس الشركة والمدراء العامون ومعاونيهم,18,0,18
2,العاملون في الامور الادارية والذاتية والاحصاء ...,9558,6,9564
3,العاملون في الحسابات والتدقيق,3561,4,3565
4,العاملون في المشتريات والاستيرادات,975,2,977
5,العاملون في المبيــعات,10055,4,10059
6,العاملون في المخــازن,3601,5,3606
7,العاملون في الشعب الفنيــــة,6302,4,6306
8,العاملون في شعبة الصيانة والتصليح والانتاج,8311,6,8317
9,العاملون في الخـدمــات,6204,5,6209
10,المجموع,48585,36,48621
12,توزيع العاملين في نهاية السنة حسب الجنس والصن...,NaN,NaN,NaN
14,اصناف العاملين,ذكور,اناث,المجموع
15,رئيس الشركة والمدراء العامون ومعاونيهم,18,0,18
16,العاملون في الامور الادارية والذاتية والاحصاء ...,6249,3315,9564
17,العاملون في الحسابات والتدقيق,2070,1495,3565
18,العاملون في المشتريات والاستيرادات,610,367,977
19,العاملون في المبيــعات,7968,2091,10059
20,العاملون في المخــازن,2534,1072,3606
21,العاملون في الشعب الفنيــــة,4871,1435,6306
22,العاملون في شعبة الصيانة والتصليح والانتاج,7347,970,8317
23,العاملون في الخـدمــات,5598,611,6209
24,المجموع,37265,11356,48621

In [30]:
df_1 = excel_df.iloc[11:,:].copy()
excel_df.drop(index=df_1.index,inplace=True)
excel_df

,توزيع العاملين في نهاية السنة حسب الجنسية والصنف لسنة 2015,العراقيون,العرب,المجموع
1,رئيس الشركة والمدراء العامون ومعاونيهم,18,0,18
2,العاملون في الامور الادارية والذاتية والاحصاء ...,9558,6,9564
3,العاملون في الحسابات والتدقيق,3561,4,3565
4,العاملون في المشتريات والاستيرادات,975,2,977
5,العاملون في المبيــعات,10055,4,10059
6,العاملون في المخــازن,3601,5,3606
7,العاملون في الشعب الفنيــــة,6302,4,6306
8,العاملون في شعبة الصيانة والتصليح والانتاج,8311,6,8317
9,العاملون في الخـدمــات,6204,5,6209
10,المجموع,48585,36,48621
12,توزيع العاملين في نهاية السنة حسب الجنس والصن...,NaN,NaN,NaN

In [31]:
excel_df.drop(index=12,inplace=True)

In [32]:
excel_df

,توزيع العاملين في نهاية السنة حسب الجنسية والصنف لسنة 2015,العراقيون,العرب,المجموع
1,رئيس الشركة والمدراء العامون ومعاونيهم,18,0,18
2,العاملون في الامور الادارية والذاتية والاحصاء ...,9558,6,9564
3,العاملون في الحسابات والتدقيق,3561,4,3565
4,العاملون في المشتريات والاستيرادات,975,2,977
5,العاملون في المبيــعات,10055,4,10059
6,العاملون في المخــازن,3601,5,3606
7,العاملون في الشعب الفنيــــة,6302,4,6306
8,العاملون في شعبة الصيانة والتصليح والانتاج,8311,6,8317
9,العاملون في الخـدمــات,6204,5,6209
10,المجموع,48585,36,48621

### Excel Output

In [34]:
excel_df.to_excel('Excel_Fixed.xlsx',sheet_name='Sheet1')

## HTML

You may need to install htmllib5,lxml, and BeautifulSoup4. In your terminal/command prompt run:

    conda install lxml
    conda install html5lib
    conda install BeautifulSoup4

Then restart Jupyter Notebook.
(or use pip install if you aren't using the Anaconda Distribution)

Pandas can read table tabs off of html. For example:

### HTML Input

Pandas read_html function will read tables off of a webpage and return a list of DataFrame objects:

In [35]:
df = pd.read_html('https://www.fdic.gov/bank-failures/failed-bank-list?combine=&items_per_page=10') #Task using this link
print(df)

[                               Bank Name           City         State   Cert  \
0           The Santa Anna National Bank     Santa Anna         Texas   5520
1                   Pulaski Savings Bank        Chicago      Illinois  28611
2     The First National Bank of Lindsay        Lindsay      Oklahoma   4134
3  Republic First Bank dba Republic Bank   Philadelphia  Pennsylvania  27332
4                          Citizens Bank       Sac City          Iowa   8758
5               Heartland Tri-State Bank        Elkhart        Kansas  25851
6                    First Republic Bank  San Francisco    California  59017
7                         Signature Bank       New York      New York  57053
8                    Silicon Valley Bank    Santa Clara    California  24735
9                      Almena State Bank         Almena        Kansas  15426

                 Acquiring Institution      Closing Date  Fund  Sort ascending
0            Coleman County State Bank     June 27, 2025                 10549
1                      Millennium Bank  January 17, 2025                 10548
2               First Bank & Trust Co.  October 18, 2024                 10547
3    Fulton Bank, National Association    April 26, 2024                 10546
4            Iowa Trust & Savings Bank  November 3, 2023                 10545
5               Dream First Bank, N.A.     July 28, 2023                 10544
6            JPMorgan Chase Bank, N.A.       May 1, 2023                 10543
7                  Flagstar Bank, N.A.    March 12, 2023                 10540
8  First Citizens Bank & Trust Company    March 10, 2023                 10539
9                          Equity Bank  October 23, 2020                 10538  ]

In [36]:
print(len(df))

1

In [37]:
print(len(df[0]))

10

In [38]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
5,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
6,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
7,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
8,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
9,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538

____

_____
_____
# SQL

The pandas.io.sql module provides a collection of query wrappers to both facilitate data retrieval and to reduce dependency on DB-specific API. Database abstraction is provided by SQLAlchemy if installed. In addition you will need a driver library for your database. Examples of such drivers are psycopg2 for PostgreSQL or pymysql for MySQL. For SQLite this is included in Python’s standard library by default. You can find an overview of supported drivers for each SQL dialect in the SQLAlchemy docs.


If SQLAlchemy is not installed, a fallback is only provided for sqlite (and for mysql for backwards compatibility, but this is deprecated and will be removed in a future version). This mode requires a Python database adapter which respect the Python DB-API.

See also some cookbook examples for some advanced strategies.

The key functions are:

* read_sql_table(table_name, con[, schema, ...])
    * Read SQL database table into a DataFrame.
* read_sql_query(sql, con[, index_col, ...])
    * Read SQL query into a DataFrame.
* read_sql(sql, con[, index_col, ...])
    * Read SQL query or database table into a DataFrame.
* DataFrame.to_sql(name, con[, flavor, ...])
    * Write records stored in a DataFrame to a SQL database.

In [39]:
from sqlalchemy import create_engine

In [40]:
engine = create_engine('sqlite:///:memory:')

In [41]:
df1= df[0]
df1.to_sql('data', engine, index=False) # Why the error?

10

In [42]:
sql_df = pd.read_sql('data', con=engine)

In [43]:
sql_df

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
5,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
6,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
7,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
8,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
9,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538

# Great Job!