# Pandas (Grouping, Aggregations and Operations)

This Notebook includes the following contents:

* Useful Function.

  - head(), tail(), dtypes, info(), shape, set_index(), reset_index(), loc(), unique(), nunique(), value_counts(), columns, rename(columns =), describe()

* Aggregation functions.
  
  - mean(), round(), max()

* groupby in Pandas.

  - groupby(), agg()

* Pivot Table

# Data

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("ds_salaries.csv")

In [5]:
df

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
...,...,...,...,...,...,...,...,...,...,...,...,...
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [6]:
df.drop(columns="Unnamed: 0",inplace=True)

In [7]:
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
...,...,...,...,...,...,...,...,...,...,...,...
602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [8]:
# Generate a new column
df['bounce'] = df['salary_in_usd'] - 700

In [9]:
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,bounce
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,79133
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,259300
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,108324
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S,19300
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L,149300
...,...,...,...,...,...,...,...,...,...,...,...,...
602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M,153300
603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M,125300
604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M,128300
605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M,149300
606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L,199300

# Useful functions

In [10]:
# first n rows
df.head() # inside you can set how many rows you need to display by default 5

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,bounce
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,79133
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,259300
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,108324
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S,19300
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L,149300

In [11]:
# last n rows
df.tail()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,bounce
602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M,153300
603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M,125300
604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M,128300
605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M,149300
606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L,199300

In [12]:
df.head(10)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,bounce
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,79133
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,259300
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,108324
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S,19300
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L,149300
5,2020,EN,FT,Data Analyst,72000,USD,72000,US,100,US,L,71300
6,2020,SE,FT,Lead Data Scientist,190000,USD,190000,US,100,US,S,189300
7,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L,35035
8,2020,MI,FT,Business Data Analyst,135000,USD,135000,US,100,US,L,134300
9,2020,SE,FT,Lead Data Engineer,125000,USD,125000,NZ,50,NZ,S,124300

In [13]:
df.head(100)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,bounce
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,79133
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,259300
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,108324
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S,19300
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L,149300
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2021,MI,FT,Cloud Data Engineer,120000,SGD,89294,SG,50,SG,L,88594
96,2021,EN,PT,AI Scientist,12000,USD,12000,BR,100,US,S,11300
97,2021,MI,FT,Financial Data Analyst,450000,USD,450000,US,100,US,L,449300
98,2021,EN,FT,Computer Vision Software Engineer,70000,USD,70000,US,100,US,M,69300
99,2021,MI,FT,Computer Vision Software Engineer,81000,EUR,95746,DE,100,US,S,95046

In [14]:
# check dtypes of columns
df.dtypes

work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
bounce                 int64
dtype: object

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           607 non-null    int64
 1   experience_level    607 non-null    object
 2   employment_type     607 non-null    object
 3   job_title           607 non-null    object
 4   salary              607 non-null    int64
 5   salary_currency     607 non-null    object
 6   salary_in_usd       607 non-null    int64
 7   employee_residence  607 non-null    object
 8   remote_ratio        607 non-null    int64
 9   company_location    607 non-null    object
 10  company_size        607 non-null    object
 11  bounce              607 non-null    int64
dtypes: int64(5), object(7)
memory usage: 57.0+ KB

In [16]:
# shape of the data frame (rows ,columns)
df.shape

(607, 12)

In [25]:
indexed_data = df.set_index("experience_level")
indexed_data

,work_year,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,bounce
experience_level,,,,,,,,,,,
MI,2020,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,79133
SE,2020,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,259300
SE,2020,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,108324
MI,2020,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S,19300
SE,2020,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L,149300
...,...,...,...,...,...,...,...,...,...,...,...
SE,2022,FT,Data Engineer,154000,USD,154000,US,100,US,M,153300
SE,2022,FT,Data Engineer,126000,USD,126000,US,100,US,M,125300
SE,2022,FT,Data Analyst,129000,USD,129000,US,0,US,M,128300
SE,2022,FT,Data Analyst,150000,USD,150000,US,100,US,M,149300
MI,2022,FT,AI Scientist,200000,USD,200000,IN,100,US,L,199300

In [18]:
indexed_data_2 = df.set_index("employee_residence")
indexed_data_2

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,remote_ratio,company_location,company_size,bounce
employee_residence,,,,,,,,,,,
DE,2020,MI,FT,Data Scientist,70000,EUR,79833,0,DE,L,79133
JP,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,0,JP,S,259300
GB,2020,SE,FT,Big Data Engineer,85000,GBP,109024,50,GB,M,108324
HN,2020,MI,FT,Product Data Analyst,20000,USD,20000,0,HN,S,19300
US,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,50,US,L,149300
...,...,...,...,...,...,...,...,...,...,...,...
US,2022,SE,FT,Data Engineer,154000,USD,154000,100,US,M,153300
US,2022,SE,FT,Data Engineer,126000,USD,126000,100,US,M,125300
US,2022,SE,FT,Data Analyst,129000,USD,129000,0,US,M,128300
US,2022,SE,FT,Data Analyst,150000,USD,150000,100,US,M,149300
IN,2022,MI,FT,AI Scientist,200000,USD,200000,100,US,L,199300

In [26]:
indexed_data.loc['MI','job_title'].head() #What will this one return?

experience_level
MI           Data Scientist
MI     Product Data Analyst
MI           Data Scientist
MI    Business Data Analyst
MI           Data Scientist
Name: job_title, dtype: object

In [27]:
# reset index is used to reset the index
indexed_data = indexed_data.reset_index()
indexed_data.head() # No need to copy previous index as it was 0,1,2,3,.....

,experience_level,work_year,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,bounce
0,MI,2020,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,79133
1,SE,2020,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,259300
2,SE,2020,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,108324
3,MI,2020,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S,19300
4,SE,2020,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L,149300

In [28]:
# get unique values of a specific column
# df['experience_level'].unique()

# you can convert it to a list and store it in a variable by using tolist()
unique_experience_level = df['experience_level'].unique().tolist()
unique_experience_level

['MI', 'SE', 'EN', 'EX']

In [29]:
# get number of unique items in a specific column
df['experience_level'].nunique()

# real world use case : retail store to count the number of customers i have

4

#Imagine we don't have nunique function what would you do?

In [30]:
len(df['experience_level'].unique())

4

In [39]:
df['experience_level'].value_counts()

experience_level
SE    280
MI    213
EN     88
EX     26
Name: count, dtype: int64

In [40]:
df['experience_level'].value_counts().count()

np.int64(4)

In [41]:
# value counts:

df['job_title'].value_counts()

job_title
Data Scientist                              143
Data Engineer                               132
Data Analyst                                 97
Machine Learning Engineer                    41
Research Scientist                           16
Data Science Manager                         12
Data Architect                               11
Machine Learning Scientist                    8
Big Data Engineer                             8
Director of Data Science                      7
AI Scientist                                  7
Principal Data Scientist                      7
Data Science Consultant                       7
Data Analytics Manager                        7
BI Data Analyst                               6
Computer Vision Engineer                      6
ML Engineer                                   6
Lead Data Engineer                            6
Applied Data Scientist                        5
Business Data Analyst                         5
Data Engineering Manager                      5
Head of Data                                  5
Data Analytics Engineer                       4
Head of Data Science                          4
Applied Machine Learning Scientist            4
Analytics Engineer                            4
Machine Learning Developer                    3
Data Science Engineer                         3
Lead Data Analyst                             3
Machine Learning Infrastructure Engineer      3
Lead Data Scientist                           3
Principal Data Engineer                       3
Computer Vision Software Engineer             3
Product Data Analyst                          2
ETL Developer                                 2
Cloud Data Engineer                           2
Financial Data Analyst                        2
Director of Data Engineering                  2
Principal Data Analyst                        2
Machine Learning Manager                      1
Marketing Data Analyst                        1
3D Computer Vision Researcher                 1
Finance Data Analyst                          1
Data Specialist                               1
Staff Data Scientist                          1
Big Data Architect                            1
Head of Machine Learning                      1
NLP Engineer                                  1
Lead Machine Learning Engineer                1
Data Analytics Lead                           1
Name: count, dtype: int64

In [42]:
df['job_title'].value_counts().count()

np.int64(50)

In [43]:
# get all columns
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size', 'bounce'],
      dtype='object')

In [44]:
# you can convert it to a list
columns = df.columns.tolist()
columns

['work_year',
 'experience_level',
 'employment_type',
 'job_title',
 'salary',
 'salary_currency',
 'salary_in_usd',
 'employee_residence',
 'remote_ratio',
 'company_location',
 'company_size',
 'bounce']

In [45]:
# rename columns (rename methode takes in a dictionary, key represents what you need to replace and value represents the new name)

df = df.rename(columns = {"work_year":"year"})
df.head(1)

,year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,bounce
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,79133

# Aggregation functions

In [46]:
# Avarage salraies
avg_salaries = df['salary_in_usd'].mean() # you can choose (mean,median,mode,std,max,min,sum)
print(f"Avarage salary in usd is  ${round(avg_salaries)}")

Avarage salary in usd is  $112298

In [50]:
# Max salary
max_salary = df['salary_in_usd'].max()
print(f"max salary in usd is  ${max_salary}")

max salary in usd is  $600000

# Task
How to get the job title of the person getting the highest salary??

In [53]:
max_salary = df['salary_in_usd'].max()
job_title = df[df['salary_in_usd'] == max_salary]['job_title'].iloc[0]  #[['job_title', 'experience_level']]
print(f"Person with the highest salary ${max_salary} is", job_title)

Person with the highest salary $600000 is Principal Data Engineer

In [57]:
job_title = df[df['salary_in_usd'] == max_salary]['job_title']
job_title

252    Principal Data Engineer
Name: job_title, dtype: object

In [58]:
job_title = df[df['salary_in_usd'] == max_salary]['job_title'].iloc[0]
job_title

'Principal Data Engineer'

In [59]:
df[df["salary_in_usd"] == df['salary_in_usd'].max() ]

,year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,bounce
252,2021,EX,FT,Principal Data Engineer,600000,USD,600000,US,100,US,L,599300

In [60]:
df[df["year"]== 2020]

,year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,bounce
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,79133
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,259300
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,108324
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S,19300
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L,149300
...,...,...,...,...,...,...,...,...,...,...,...,...
67,2020,SE,FT,Data Science Manager,190200,USD,190200,US,100,US,M,189500
68,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S,104300
69,2020,SE,FT,Data Scientist,80000,EUR,91237,AT,0,AT,S,90537
70,2020,MI,FT,Data Scientist,55000,EUR,62726,FR,50,LU,S,62026
71,2020,MI,FT,Data Scientist,37000,EUR,42197,FR,50,FR,S,41497

In [61]:
# describe
df.describe() # it takes all numerical columns and returns a summary statistics

              year        salary  salary_in_usd  remote_ratio         bounce
count   607.000000  6.070000e+02     607.000000     607.00000     607.000000
mean   2021.405272  3.240001e+05  112297.869852      70.92257  111597.869852
std       0.692133  1.544357e+06   70957.259411      40.70913   70957.259411
min    2020.000000  4.000000e+03    2859.000000       0.00000    2159.000000
25%    2021.000000  7.000000e+04   62726.000000      50.00000   62026.000000
50%    2022.000000  1.150000e+05  101570.000000     100.00000  100870.000000
75%    2022.000000  1.650000e+05  150000.000000     100.00000  149300.000000
max    2022.000000  3.040000e+07  600000.000000     100.00000  599300.000000

#Task
Write a code to describe only salary and remote_ratio

In [62]:
df[["salary", "remote_ratio"]].describe()

             salary  remote_ratio
count  6.070000e+02     607.00000
mean   3.240001e+05      70.92257
std    1.544357e+06      40.70913
min    4.000000e+03       0.00000
25%    7.000000e+04      50.00000
50%    1.150000e+05     100.00000
75%    1.650000e+05     100.00000
max    3.040000e+07     100.00000

# groupby in Pandas

**The groupby operation in pandas is a powerful tool used to split your data into groups based on some criteria, apply a function to each group, and combine the results. It's similar to the split-apply-combine strategy:**

*   Split: The data is split into groups based on some column(s).
*   Apply: A function is applied to each group independently.


*   Combine: The results are combined back into a DataFrame or Series.

**Why Use groupby?**



*   It helps you explore and analyze data by grouping similar items.

*   You can calculate summary statistics (like mean, sum, count, etc.) for groups of data.


*   It is especially useful for handling time series, categorical data, or datasets where you need to aggregate by a specific feature.

In [63]:
df['job_title']

0                  Data Scientist
1      Machine Learning Scientist
2               Big Data Engineer
3            Product Data Analyst
4       Machine Learning Engineer
                  ...
602                 Data Engineer
603                 Data Engineer
604                  Data Analyst
605                  Data Analyst
606                  AI Scientist
Name: job_title, Length: 607, dtype: object

In [64]:
"""
Grouping by a Single Column
Problem: Find the average salary for each job title.
"""

# option 1

average_salary_by_job = df.groupby('job_title')['salary_in_usd'].mean()
average_salary_by_job

job_title
3D Computer Vision Researcher                 5409.000000
AI Scientist                                 66135.571429
Analytics Engineer                          175000.000000
Applied Data Scientist                      175655.000000
Applied Machine Learning Scientist          142068.750000
BI Data Analyst                              74755.166667
Big Data Architect                           99703.000000
Big Data Engineer                            51974.000000
Business Data Analyst                        76691.200000
Cloud Data Engineer                         124647.000000
Computer Vision Engineer                     44419.333333
Computer Vision Software Engineer           105248.666667
Data Analyst                                 92893.061856
Data Analytics Engineer                      64799.250000
Data Analytics Lead                         405000.000000
Data Analytics Manager                      127134.285714
Data Architect                              177873.909091
Data Engineer                               112725.000000
Data Engineering Manager                    123227.200000
Data Science Consultant                      69420.714286
Data Science Engineer                        75803.333333
Data Science Manager                        158328.500000
Data Scientist                              108187.832168
Data Specialist                             165000.000000
Director of Data Engineering                156738.000000
Director of Data Science                    195074.000000
ETL Developer                                54957.000000
Finance Data Analyst                         61896.000000
Financial Data Analyst                      275000.000000
Head of Data                                160162.600000
Head of Data Science                        146718.750000
Head of Machine Learning                     79039.000000
Lead Data Analyst                            92203.000000
Lead Data Engineer                          139724.500000
Lead Data Scientist                         115190.000000
Lead Machine Learning Engineer               87932.000000
ML Engineer                                 117504.000000
Machine Learning Developer                   85860.666667
Machine Learning Engineer                   104880.146341
Machine Learning Infrastructure Engineer    101145.000000
Machine Learning Manager                    117104.000000
Machine Learning Scientist                  158412.500000
Marketing Data Analyst                       88654.000000
NLP Engineer                                 37236.000000
Principal Data Analyst                      122500.000000
Principal Data Engineer                     328333.333333
Principal Data Scientist                    215242.428571
Product Data Analyst                         13036.000000
Research Scientist                          109019.500000
Staff Data Scientist                        105000.000000
Name: salary_in_usd, dtype: float64

In [65]:
average_salary_by_job.count()

np.int64(50)

In [66]:
# option 2
average_salary_by_job = df.groupby('job_title').agg({"salary_in_usd":"mean"})
average_salary_by_job

                                          salary_in_usd
job_title
3D Computer Vision Researcher               5409.000000
AI Scientist                               66135.571429
Analytics Engineer                        175000.000000
Applied Data Scientist                    175655.000000
Applied Machine Learning Scientist        142068.750000
BI Data Analyst                            74755.166667
Big Data Architect                         99703.000000
Big Data Engineer                          51974.000000
Business Data Analyst                      76691.200000
Cloud Data Engineer                       124647.000000
Computer Vision Engineer                   44419.333333
Computer Vision Software Engineer         105248.666667
Data Analyst                               92893.061856
Data Analytics Engineer                    64799.250000
Data Analytics Lead                       405000.000000
Data Analytics Manager                    127134.285714
Data Architect                            177873.909091
Data Engineer                             112725.000000
Data Engineering Manager                  123227.200000
Data Science Consultant                    69420.714286
Data Science Engineer                      75803.333333
Data Science Manager                      158328.500000
Data Scientist                            108187.832168
Data Specialist                           165000.000000
Director of Data Engineering              156738.000000
Director of Data Science                  195074.000000
ETL Developer                              54957.000000
Finance Data Analyst                       61896.000000
Financial Data Analyst                    275000.000000
Head of Data                              160162.600000
Head of Data Science                      146718.750000
Head of Machine Learning                   79039.000000
Lead Data Analyst                          92203.000000
Lead Data Engineer                        139724.500000
Lead Data Scientist                       115190.000000
Lead Machine Learning Engineer             87932.000000
ML Engineer                               117504.000000
Machine Learning Developer                 85860.666667
Machine Learning Engineer                 104880.146341
Machine Learning Infrastructure Engineer  101145.000000
Machine Learning Manager                  117104.000000
Machine Learning Scientist                158412.500000
Marketing Data Analyst                     88654.000000
NLP Engineer                               37236.000000
Principal Data Analyst                    122500.000000
Principal Data Engineer                   328333.333333
Principal Data Scientist                  215242.428571
Product Data Analyst                       13036.000000
Research Scientist                        109019.500000
Staff Data Scientist                      105000.000000

In [67]:
a = average_salary_by_job.count()
print(a)

salary_in_usd    50
dtype: int64

In [68]:
# Find the total salary paid for each combination of experience_level and employment_type.

total_salary_by_experience_employment = df.groupby(['experience_level', 'employment_type'])['salary_in_usd'].sum()
total_salary_by_experience_employment

experience_level  employment_type
EN                CT                   131875
                  FT                  5092139
                  PT                   200598
EX                CT                   416000
                  FT                  4768193
MI                CT                   270000
                  FL                   132000
                  FT                 18211053
                  PT                   130107
SE                CT                   105000
                  FL                    60000
                  FT                 38647842
Name: salary_in_usd, dtype: int64

In [69]:
df.head(1)

,year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,bounce
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L,79133

In [70]:
df.groupby(["company_location", "company_size"])['salary_in_usd'].median()

company_location  company_size
AE                L               115000.0
                  S                92500.0
AS                S                18053.0
AT                L                69489.5
                  M                61467.0
                                    ...
UA                L                13400.0
US                L               150000.0
                  M               135500.0
                  S                90000.0
VN                M                 4000.0
Name: salary_in_usd, Length: 84, dtype: float64

In [71]:
# Use groupby to find the median salary in USD for each company location and company size
median_salary = df.groupby(['company_location', 'company_size'])['salary_in_usd'].median()
median_salary.reset_index()

   company_location company_size  salary_in_usd
0                AE            L       115000.0
1                AE            S        92500.0
2                AS            S        18053.0
3                AT            L        69489.5
4                AT            M        61467.0
..              ...          ...            ...
79               UA            L        13400.0
80               US            L       150000.0
81               US            M       135500.0
82               US            S        90000.0
83               VN            M         4000.0

[84 rows x 3 columns]

In [72]:
df.columns

Index(['year', 'experience_level', 'employment_type', 'job_title', 'salary',
       'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size', 'bounce'],
      dtype='object')

# Task : find the total and average salary for each job_title

You can perform multiple operations on different columns within the same group using the agg() function like what we have seen above

In [73]:
# approach one

salary_stats_by_job = df.groupby('job_title').agg({"salary_in_usd":['mean','median']})
salary_stats_by_job.reset_index()

                                   job_title  salary_in_usd
                                                       mean    median
0              3D Computer Vision Researcher    5409.000000    5409.0
1                               AI Scientist   66135.571429   45896.0
2                         Analytics Engineer  175000.000000  179850.0
3                     Applied Data Scientist  175655.000000  157000.0
4         Applied Machine Learning Scientist  142068.750000   56700.0
5                            BI Data Analyst   74755.166667   76500.0
6                         Big Data Architect   99703.000000   99703.0
7                          Big Data Engineer   51974.000000   41305.5
8                      Business Data Analyst   76691.200000   70912.0
9                        Cloud Data Engineer  124647.000000  124647.0
10                  Computer Vision Engineer   44419.333333   26304.5
11         Computer Vision Software Engineer  105248.666667   95746.0
12                              Data Analyst   92893.061856   90320.0
13                   Data Analytics Engineer   64799.250000   64598.5
14                       Data Analytics Lead  405000.000000  405000.0
15                    Data Analytics Manager  127134.285714  120000.0
16                            Data Architect  177873.909091  180000.0
17                             Data Engineer  112725.000000  105500.0
18                  Data Engineering Manager  123227.200000  150000.0
19                   Data Science Consultant   69420.714286   76833.0
20                     Data Science Engineer   75803.333333   60000.0
21                      Data Science Manager  158328.500000  155750.0
22                            Data Scientist  108187.832168  103691.0
23                           Data Specialist  165000.000000  165000.0
24              Director of Data Engineering  156738.000000  156738.0
25                  Director of Data Science  195074.000000  168000.0
26                             ETL Developer   54957.000000   54957.0
27                      Finance Data Analyst   61896.000000   61896.0
28                    Financial Data Analyst  275000.000000  275000.0
29                              Head of Data  160162.600000  200000.0
30                      Head of Data Science  146718.750000  138937.5
31                  Head of Machine Learning   79039.000000   79039.0
32                         Lead Data Analyst   92203.000000   87000.0
33                        Lead Data Engineer  139724.500000  121593.5
34                       Lead Data Scientist  115190.000000  115000.0
35            Lead Machine Learning Engineer   87932.000000   87932.0
36                               ML Engineer  117504.000000   70537.5
37                Machine Learning Developer   85860.666667   78791.0
38                 Machine Learning Engineer  104880.146341   87932.0
39  Machine Learning Infrastructure Engineer  101145.000000   58255.0
40                  Machine Learning Manager  117104.000000  117104.0
41                Machine Learning Scientist  158412.500000  156500.0
42                    Marketing Data Analyst   88654.000000   88654.0
43                              NLP Engineer   37236.000000   37236.0
44                    Principal Data Analyst  122500.000000  122500.0
45                   Principal Data Engineer  328333.333333  200000.0
46                  Principal Data Scientist  215242.428571  173762.0
47                      Product Data Analyst   13036.000000   13036.0
48                        Research Scientist  109019.500000   76263.5
49                      Staff Data Scientist  105000.000000  105000.0

In [74]:
# approach two (recommended)
salary_stats_by_job = df.groupby('job_title').agg(
    total_salary=('salary', 'sum'),
    average_salary=('salary', 'mean'),
)

salary_stats_by_job

                                          total_salary  average_salary
job_title
3D Computer Vision Researcher                   400000    4.000000e+05
AI Scientist                                   2034000    2.905714e+05
Analytics Engineer                              700000    1.750000e+05
Applied Data Scientist                          862000    1.724000e+05
Applied Machine Learning Scientist              565400    1.413500e+05
BI Data Analyst                               11412272    1.902045e+06
Big Data Architect                              125000    1.250000e+05
Big Data Engineer                              3640000    4.550000e+05
Business Data Analyst                          1775000    3.550000e+05
Cloud Data Engineer                             280000    1.400000e+05
Computer Vision Engineer                        501000    8.350000e+04
Computer Vision Software Engineer               301000    1.003333e+05
Data Analyst                                   9370681    9.660496e+04
Data Analytics Engineer                         247000    6.175000e+04
Data Analytics Lead                             405000    4.050000e+05
Data Analytics Manager                          889940    1.271343e+05
Data Architect                                 1956613    1.778739e+05
Data Engineer                                 23655793    1.792106e+05
Data Engineering Manager                        598999    1.197998e+05
Data Science Consultant                         859000    1.227143e+05
Data Science Engineer                           253500    8.450000e+04
Data Science Manager                          12751183    1.062599e+06
Data Scientist                                72693650    5.083472e+05
Data Specialist                                 165000    1.650000e+05
Director of Data Engineering                    282500    1.412500e+05
Director of Data Science                       1353000    1.932857e+05
ETL Developer                                   100000    5.000000e+04
Finance Data Analyst                             45000    4.500000e+04
Financial Data Analyst                          550000    2.750000e+05
Head of Data                                    782000    1.564000e+05
Head of Data Science                            586875    1.467188e+05
Head of Machine Learning                       6000000    6.000000e+06
Lead Data Analyst                              1707000    5.690000e+05
Lead Data Engineer                              842000    1.403333e+05
Lead Data Scientist                            3305000    1.101667e+06
Lead Machine Learning Engineer                   80000    8.000000e+04
ML Engineer                                   16060000    2.676667e+06
Machine Learning Developer                      300000    1.000000e+05
Machine Learning Engineer                     11181433    2.727179e+05
Machine Learning Infrastructure Engineer        292000    9.733333e+04
Machine Learning Manager                        157000    1.570000e+05
Machine Learning Scientist                     1267300    1.584125e+05
Marketing Data Analyst                           75000    7.500000e+04
NLP Engineer                                    240000    2.400000e+05
Principal Data Analyst                          245000    1.225000e+05
Principal Data Engineer                         985000    3.283333e+05
Principal Data Scientist                       1447000    2.067143e+05
Product Data Analyst                            470000    2.350000e+05
Research Scientist                             1767899    1.104937e+05
Staff Data Scientist                            105000    1.050000e+05

In [75]:
# find the total and average for (salary and salary_in_usd) for each job_title and experience level  using the recommended way
y=df.groupby(['job_title','experience_level']).agg(
    total_salary=('salary','sum'),
    average_salary=('salary','mean'),
    total_salary_in_usd=('salary_in_usd','sum'),
    average_salary_in_usd=('salary_in_usd','mean')

)
y

                                                total_salary  average_salary  \
job_title                     experience_level
3D Computer Vision Researcher MI                      400000   400000.000000
AI Scientist                  EN                     1659000   414750.000000
                              MI                      320000   160000.000000
                              SE                       55000    55000.000000
Analytics Engineer            EX                      310000   155000.000000
...                                                      ...             ...
Product Data Analyst          MI                      470000   235000.000000
Research Scientist            EN                      322000    80500.000000
                              MI                      994999   142142.714286
                              SE                      450900    90180.000000
Staff Data Scientist          SE                      105000   105000.000000

                                                total_salary_in_usd  \
job_title                     experience_level
3D Computer Vision Researcher MI                               5409
AI Scientist                  EN                              87949
                              MI                             320000
                              SE                              55000
Analytics Engineer            EX                             310000
...                                                             ...
Product Data Analyst          MI                              26072
Research Scientist            EN                             344528
                              MI                             955487
                              SE                             444297
Staff Data Scientist          SE                             105000

                                                average_salary_in_usd
job_title                     experience_level
3D Computer Vision Researcher MI                          5409.000000
AI Scientist                  EN                         21987.250000
                              MI                        160000.000000
                              SE                         55000.000000
Analytics Engineer            EX                        155000.000000
...                                                               ...
Product Data Analyst          MI                         13036.000000
Research Scientist            EN                         86132.000000
                              MI                        136498.142857
                              SE                         88859.400000
Staff Data Scientist          SE                        105000.000000

[105 rows x 4 columns]

In [82]:
# Count the number of employees in each country (employee_residence)
employee_count_by_residence = df.groupby('employee_residence').size()
employee_count_by_residence

employee_residence
AE      3
AR      1
AT      3
AU      3
BE      2
BG      1
BO      1
BR      6
CA     29
CH      1
CL      1
CN      1
CO      1
CZ      1
DE     25
DK      2
DZ      1
EE      1
ES     15
FR     18
GB     44
GR     13
HK      1
HN      1
HR      1
HU      2
IE      1
IN     30
IQ      1
IR      1
IT      4
JE      1
JP      7
KE      1
LU      1
MD      1
MT      1
MX      2
MY      1
NG      2
NL      5
NZ      1
PH      1
PK      6
PL      4
PR      1
PT      6
RO      2
RS      1
RU      4
SG      2
SI      2
TN      1
TR      3
UA      1
US    332
VN      3
dtype: int64

# Task

1. Group the data by both employee_residence and experience_level.

2. For each group, calculate:
* The average salary (salary_in_usd)
* The number of employees
* The maximum salary

Rename the resulting columns to:

'avg_salary'

'employee_count'

'max_salary'

3. Sort the result by average salary in descending order.

4. Return only the top 10 rows.

Bonus:
* Only include rows where employment_type is 'FT'

In [93]:
salary_summary = df[df['employment_type'] == 'FT']
salary_summary = df.groupby(['employee_residence', 'experience_level']).agg(
    avg_salary=('salary_in_usd', 'mean'),
    employee_count=('salary_in_usd', 'count'),
    max_salary=('salary_in_usd', 'max')
).sort_values(by='avg_salary', ascending=False)

In [94]:
salary_summary.head(10)

                                        avg_salary  employee_count  max_salary
employee_residence experience_level
US                 EX                249991.666667              15      600000
JP                 SE                214000.000000               2      260000
MY                 SE                200000.000000               1      200000
PR                 SE                160000.000000               1      160000
CA                 EX                157583.000000               2      196979
RU                 EX                157500.000000               2      230000
US                 SE                153921.810427             211      412000
IT                 EX                153667.000000               1      153667
DE                 EX                135936.000000               2      141846
US                 MI                135617.792208              77      450000

# Pivot Table

In [95]:
import pandas as pd

In [96]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [97]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [98]:
df.pivot_table(values='D', index=['A', 'B'])

           D
A   B
bar one  2.5
    two  5.0
foo one  2.0
    two  2.0

In [99]:
df.groupby(['A', 'B'])['D'].mean()

A    B
bar  one    2.5
     two    5.0
foo  one    2.0
     two    2.0
Name: D, dtype: float64

In [100]:
df.pivot_table(values='D', index=['A', 'B'], aggfunc= 'sum')

         D
A   B
bar one  5
    two  5
foo one  4
    two  2

In [101]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [102]:
df.pivot_table(values='D', index=['A', 'B'], columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

# Task
```
import pandas as pd

data = {
    'Region': ['North', 'North', 'South', 'South', 'East', 'East', 'West', 'West', 'North', 'South'],
    'Product': ['Apples', 'Oranges', 'Apples', 'Bananas', 'Apples', 'Bananas', 'Oranges', 'Bananas', 'Apples', 'Oranges'],
    'Salesperson': ['Ali', 'Lina', 'Sara', 'Khalid', 'Lina', 'Ali', 'Sara', 'Khalid', 'Sara', 'Ali'],
    'Units_Sold': [50, 40, 30, 25, 20, 35, 60, 45, 40, 20]
}

```
1. Create a pivot table that shows the total units sold for each Product in each Region.

* Use Region as the rows (index)

* Use Product as the columns (columns)

* Aggregate using the sum of Units_Sold

2. create another pivot table showing the average units sold by each Salesperson for each Product.

Bonus: Replace any NaN values with 0 in the pivot tables.

In [103]:
data = {
    'Region': ['North', 'North', 'South', 'South', 'East', 'East', 'West', 'West', 'North', 'South'],
    'Product': ['Apples', 'Oranges', 'Apples', 'Bananas', 'Apples', 'Bananas', 'Oranges', 'Bananas', 'Apples', 'Oranges'],
    'Salesperson': ['Ali', 'Lina', 'Sara', 'Khalid', 'Lina', 'Ali', 'Sara', 'Khalid', 'Sara', 'Ali'],
    'Units_Sold': [50, 40, 30, 25, 20, 35, 60, 45, 40, 20]
}

df = pd.DataFrame(data)
df

  Region  Product Salesperson  Units_Sold
0  North   Apples         Ali          50
1  North  Oranges        Lina          40
2  South   Apples        Sara          30
3  South  Bananas      Khalid          25
4   East   Apples        Lina          20
5   East  Bananas         Ali          35
6   West  Oranges        Sara          60
7   West  Bananas      Khalid          45
8  North   Apples        Sara          40
9  South  Oranges         Ali          20

In [104]:
pivot1 = df.pivot_table(
    values='Units_Sold',
    index='Region',
    columns='Product',
    aggfunc='sum'
)

pivot1

Product  Apples  Bananas  Oranges
Region
East       20.0     35.0      NaN
North      90.0      NaN     40.0
South      30.0     25.0     20.0
West        NaN     45.0     60.0

In [105]:
pivot1.fillna(0)

Product  Apples  Bananas  Oranges
Region
East       20.0     35.0      0.0
North      90.0      0.0     40.0
South      30.0     25.0     20.0
West        0.0     45.0     60.0

In [106]:
pivot2 = df.pivot_table(
    values='Units_Sold',
    index='Salesperson',
    columns='Product',
    aggfunc='mean'
).fillna(0)
pivot2

Product      Apples  Bananas  Oranges
Salesperson
Ali            50.0     35.0     20.0
Khalid          0.0     35.0      0.0
Lina           20.0      0.0     40.0
Sara           35.0      0.0     60.0

# Great Job ❤