In [1]:
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import numpy as np
import nbformat

In [2]:
df = pd.read_csv('DailyDelhiClimateTrain.csv')

In [3]:
df.head()

         date   meantemp   humidity  wind_speed  meanpressure
0  2013-01-01  10.000000  84.500000    0.000000   1015.666667
1  2013-01-02   7.400000  92.000000    2.980000   1017.800000
2  2013-01-03   7.166667  87.000000    4.633333   1018.666667
3  2013-01-04   8.666667  71.333333    1.233333   1017.166667
4  2013-01-05   6.000000  86.833333    3.700000   1016.500000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1462 non-null   object
 1   meantemp      1462 non-null   float64
 2   humidity      1462 non-null   float64
 3   wind_speed    1462 non-null   float64
 4   meanpressure  1462 non-null   float64
dtypes: float64(4), object(1)
memory usage: 57.2+ KB

In [5]:
df.shape

(1462, 5)

In [6]:
df['date'] = pd.to_datetime(df['date'])

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1462 entries, 0 to 1461
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1462 non-null   datetime64[ns]
 1   meantemp      1462 non-null   float64
 2   humidity      1462 non-null   float64
 3   wind_speed    1462 non-null   float64
 4   meanpressure  1462 non-null   float64
dtypes: datetime64[ns](1), float64(4)
memory usage: 57.2 KB

In [10]:
fig = px.line(df, x="date", y="meantemp", title='tempreture')
fig.show()

In [11]:
fig = px.line(df, x="date", y="meantemp", title='tempreture', markers=True)
fig.show()

In [12]:
df = pd.read_csv("ds_salaries.csv")

In [13]:
df

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
...,...,...,...,...,...,...,...,...,...,...,...,...
602,602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [14]:
df = df.drop(columns="Unnamed: 0")
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
...,...,...,...,...,...,...,...,...,...,...,...
602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [15]:
# histogram for salary distribution

fig = px.histogram(df, x='salary_in_usd', nbins=40, title='Distribution of Salary in USD') # no default for nbins
fig.show()

In [18]:
# box plot for salary by job title

fig = px.box(df, x='job_title', y='salary_in_usd', title='Salary Distribution by Job Title')
fig.update_xaxes(tickangle=45)
fig.show()

In [19]:
df

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L
...,...,...,...,...,...,...,...,...,...,...,...
602,2022,SE,FT,Data Engineer,154000,USD,154000,US,100,US,M
603,2022,SE,FT,Data Engineer,126000,USD,126000,US,100,US,M
604,2022,SE,FT,Data Analyst,129000,USD,129000,US,0,US,M
605,2022,SE,FT,Data Analyst,150000,USD,150000,US,100,US,M
606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [22]:
df.groupby('experience_level')['salary_in_usd'].mean().reset_index()

  experience_level  salary_in_usd
0               EN   61643.318182
1               EX  199392.038462
2               MI   87996.056338
3               SE  138617.292857

In [23]:
# Bar Chart for Average Salary by Experience Level

avg_salary_experience = df.groupby('experience_level')['salary_in_usd'].mean().reset_index()

fig = px.bar(avg_salary_experience, x='experience_level', y='salary_in_usd',
             title='Average Salary by Experience Level')
fig.show()

In [24]:
df.groupby('company_size')['salary_in_usd'].mean().reset_index()

  company_size  salary_in_usd
0            L  119242.994949
1            M  116905.466258
2            S   77632.674699

In [25]:
# bar chart for salary by company size
avg_salary_company_size = df.groupby('company_size')['salary_in_usd'].mean().reset_index()

fig = px.bar(avg_salary_company_size, x='company_size', y='salary_in_usd',
             title='Average Salary by Company Size')
fig.show()

# Real world data

In [26]:
df = pd.read_csv('demand_sales_data.csv')
df.dropna(inplace = True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10893 entries, 0 to 11385
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                10893 non-null  object
 1   Order_ID            10893 non-null  int64
 2   Company             10893 non-null  int64
 3   Company_Region      10893 non-null  object
 4   Product_ID          10893 non-null  int64
 5   Product             10893 non-null  object
 6   Customer_ID         10893 non-null  object
 7   Product Category01  10893 non-null  float64
 8   Product Category02  10893 non-null  object
 9   Product Category03  10893 non-null  object
 10  Quantity            10893 non-null  int64
 11  unit                10893 non-null  object
 12  price_per_case      10893 non-null  float64
dtypes: float64(2), int64(4), object(7)
memory usage: 1.2+ MB

In [28]:
df.shape

(10893, 13)

In [29]:
df.columns

Index(['date', 'Order_ID', 'Company', 'Company_Region', 'Product_ID',
       'Product', 'Customer_ID', 'Product Category01', 'Product Category02',
       'Product Category03', 'Quantity', 'unit', 'price_per_case'],
      dtype='object')

In [30]:
df = df.rename(columns = {"Product Category01":'size'})

In [31]:
df.columns

Index(['date', 'Order_ID', 'Company', 'Company_Region', 'Product_ID',
       'Product', 'Customer_ID', 'size', 'Product Category02',
       'Product Category03', 'Quantity', 'unit', 'price_per_case'],
      dtype='object')

In [32]:
df.head()

,date,Order_ID,Company,Company_Region,Product_ID,Product,Customer_ID,size,Product Category02,Product Category03,Quantity,unit,price_per_case
0,1/1/2021,6141309,121,South,11829,AVO32CNV2,DMKUT,32.0,CNV,#2,224,case,41.0
1,1/1/2021,6377268,131,North,11541,AVO60CNV1,QPDXK,60.0,CNV,1,396,case,46.0
3,1/1/2021,6191867,121,South,11829,AVO32CNV2,IEHDJ,32.0,CNV,#2,150,case,41.0
4,1/1/2021,6191867,121,South,11385,AVO48CNV2,IEHDJ,48.0,CNV,#2,294,case,49.0
5,1/1/2021,6377268,131,North,11829,AVO32CNV2,QPDXK,32.0,CNV,#2,145,case,41.0

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10893 entries, 0 to 11385
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                10893 non-null  object
 1   Order_ID            10893 non-null  int64
 2   Company             10893 non-null  int64
 3   Company_Region      10893 non-null  object
 4   Product_ID          10893 non-null  int64
 5   Product             10893 non-null  object
 6   Customer_ID         10893 non-null  object
 7   size                10893 non-null  float64
 8   Product Category02  10893 non-null  object
 9   Product Category03  10893 non-null  object
 10  Quantity            10893 non-null  int64
 11  unit                10893 non-null  object
 12  price_per_case      10893 non-null  float64
dtypes: float64(2), int64(4), object(7)
memory usage: 1.2+ MB

In [34]:
pd.to_datetime(df['date']).dt.weekday.unique()

array([4, 5, 6, 0, 1, 2, 3], dtype=int32)

In [35]:
now = pd.to_datetime(df['date'])[0]
now

Timestamp('2021-01-01 00:00:00')

In [36]:
then = pd.to_timedelta(pd.to_datetime(df['date']).dt.weekday, unit='D')[0]
then

Timedelta('4 days 00:00:00')

In [37]:
now - then

Timestamp('2020-12-28 00:00:00')

In [38]:
pd.to_timedelta(pd.to_datetime(df['date']).dt.weekday, unit='D').unique()

<TimedeltaArray>
['4 days', '5 days', '6 days', '0 days', '1 days', '2 days', '3 days']
Length: 7, dtype: timedelta64[ns]

In [39]:
df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year
df['week_of_year'] = df['date'].dt.isocalendar().week
df['week_start_dt'] = df['date'] - pd.to_timedelta(df['date'].dt.weekday, unit='D')
df

,date,Order_ID,Company,Company_Region,Product_ID,Product,Customer_ID,size,Product Category02,Product Category03,Quantity,unit,price_per_case,year,week_of_year,week_start_dt
0,2021-01-01,6141309,121,South,11829,AVO32CNV2,DMKUT,32.0,CNV,#2,224,case,41.0,2021,53,2020-12-28
1,2021-01-01,6377268,131,North,11541,AVO60CNV1,QPDXK,60.0,CNV,1,396,case,46.0,2021,53,2020-12-28
3,2021-01-01,6191867,121,South,11829,AVO32CNV2,IEHDJ,32.0,CNV,#2,150,case,41.0,2021,53,2020-12-28
4,2021-01-01,6191867,121,South,11385,AVO48CNV2,IEHDJ,48.0,CNV,#2,294,case,49.0,2021,53,2020-12-28
5,2021-01-01,6377268,131,North,11829,AVO32CNV2,QPDXK,32.0,CNV,#2,145,case,41.0,2021,53,2020-12-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11380,2023-08-20,6545429,121,South,11385,AVO48CNV2,SZYVW,48.0,CNV,#2,337,case,40.0,2023,33,2023-08-14
11381,2023-08-20,6545429,121,South,11177,AVO32ORG0,SZYVW,32.0,ORG,0,324,case,50.0,2023,33,2023-08-14
11382,2023-08-20,6545429,121,South,11385,AVO48CNV2,SZYVW,48.0,CNV,#2,124,case,40.0,2023,33,2023-08-14
11383,2023-08-20,6545429,121,South,11931,AVO48CNV1,SZYVW,48.0,CNV,1,294,case,50.0,2023,33,2023-08-14
11385,2023-08-20,6271650,131,North,11501,AVO32CNV1,DWCGE,32.0,CNV,1,300,case,46.0,2023,33,2023-08-14

In [40]:
df.groupby(['week_start_dt']).agg({"price_per_case":'sum','Quantity':'sum'}).reset_index()

    week_start_dt  price_per_case  Quantity
0      2020-12-28          1026.0      4547
1      2021-01-04          1453.0     10771
2      2021-01-11          2146.0     14055
3      2021-01-18          2492.0     16417
4      2021-01-25          2598.0     15228
..            ...             ...       ...
133    2023-07-17          2787.0     19625
134    2023-07-24          3095.0     21969
135    2023-07-31          2434.0     31924
136    2023-08-07          2050.0     18663
137    2023-08-14          1894.0     14513

[138 rows x 3 columns]

In [45]:
df_grouped = df.groupby(['week_start_dt' , 'size','Company','week_of_year',
            'year','Company_Region']).agg({"price_per_case":'sum','Quantity':'sum'}).reset_index()

df_grouped

,week_start_dt,size,Company,week_of_year,year,Company_Region,price_per_case,Quantity
0,2020-12-28,32.0,121,53,2021,South,121.0,604
1,2020-12-28,32.0,131,53,2021,North,226.0,691
2,2020-12-28,32.0,131,53,2021,South,166.0,681
3,2020-12-28,48.0,121,53,2021,South,91.0,559
4,2020-12-28,48.0,131,53,2021,North,39.0,186
...,...,...,...,...,...,...,...,...
1127,2023-08-14,48.0,131,33,2023,North,190.0,1140
1128,2023-08-14,49.0,131,33,2023,North,48.0,275
1129,2023-08-14,60.0,121,33,2023,South,170.0,1086
1130,2023-08-14,60.0,131,33,2023,North,461.0,4548
1131,2023-08-14,60.0,131,33,2023,South,75.0,135

In [46]:
df_grouped = df_grouped[df_grouped['Company'] == 121]

In [47]:
df_grouped

,week_start_dt,size,Company,week_of_year,year,Company_Region,price_per_case,Quantity
0,2020-12-28,32.0,121,53,2021,South,121.0,604
3,2020-12-28,48.0,121,53,2021,South,91.0,559
6,2020-12-28,60.0,121,53,2021,South,92.0,348
8,2021-01-04,32.0,121,1,2021,South,225.0,1090
10,2021-01-04,48.0,121,1,2021,South,467.0,4648
...,...,...,...,...,...,...,...,...
1119,2023-08-07,60.0,121,32,2023,South,88.0,540
1122,2023-08-07,600.0,121,32,2023,South,43.0,239
1123,2023-08-14,32.0,121,33,2023,South,180.0,938
1126,2023-08-14,48.0,121,33,2023,South,382.0,4166
1129,2023-08-14,60.0,121,33,2023,South,170.0,1086

In [48]:
df_grouped['size'].unique().tolist()

[32.0, 48.0, 60.0, 49.0, 50.0, 600.0]

In [55]:


# fig = make_subplots(rows=1, cols=1, shared_axes=True)
fig = go.Figure()

# List of sizes
sizes = df_grouped['size'].unique().tolist()

for size in sizes:

    filtered_data = df_grouped[(df_grouped['size'] == size) & (df_grouped['year'] == 2021)].sort_values('week_start_dt')

    fig.add_trace(go.Scatter(
        x=filtered_data['week_start_dt'],
        y=filtered_data['Quantity'],
        mode='lines+markers',  # Use both lines and markers for better visibility
        name=f'quantity Size {size}'
    ))

fig.update_layout(
    title='Quantity Trends by Size Over Time (2021) for commany 121',
    xaxis_title='Date',
    yaxis_title='Qunatity Per Case',
    # width=1000,
    # height=400,
)


fig.show()

In [56]:
fig = go.Figure()

sizes = df_grouped['size'].unique()
years = df_grouped['year'].unique()

for size in sizes:
    for year in years:
      filtered_data = df_grouped[(df_grouped['size'] == size) & (df_grouped['year'] == year) & (df_grouped['week_of_year']<=50)].sort_values('week_start_dt')
      fig.add_trace(go.Scatter(
          x=filtered_data['week_of_year'],
          y=filtered_data['Quantity'],
          mode='lines+markers',  # Use both lines and markers for better visibility
          name=f'quantity {size} year {year}'
      ))

# Update layout to improve aesthetics
fig.update_layout(
    title='Quantity Trends by Size Over Time (2021) for commany 121',
    xaxis_title='Date',
    yaxis_title='Qunatity Per Case',
    # width=1000,
    # height=400,
)


# Show the updated figure
fig.show()

In [58]:
dd = df.groupby(['Company','year']).agg({"Quantity":'sum'}).reset_index()
dd.Company.unique()
dd['Company'] = dd['Company'].astype(str)

In [59]:
dd.Company.unique()

array(['121', '131'], dtype=object)

In [60]:
dd

  Company  year  Quantity
0     121  2021    509423
1     121  2022    707619
2     121  2023    298110
3     131  2021    371559
4     131  2022    856668
5     131  2023    642898

In [61]:
fig = px.bar(dd, x='year', y='Quantity', color='Company',text="Company",title = 'total Quantity over the years per company')

fig.show()

In [67]:
dd2 = df.groupby(['Company','year','size']).agg({"Quantity":'sum'}).reset_index()

In [68]:
dd2['Company'] = dd2['Company'].astype(str)

In [69]:
dd2

   Company  year   size  Quantity
0      121  2021   32.0    140233
1      121  2021   48.0    297614
2      121  2021   49.0       641
3      121  2021   50.0       672
4      121  2021   60.0     70263
5      121  2022   32.0    241465
6      121  2022   48.0    350635
7      121  2022   60.0    115519
8      121  2023   32.0     83995
9      121  2023   48.0    186036
10     121  2023   60.0     27840
11     121  2023  600.0       239
12     131  2021   32.0     73001
13     131  2021   48.0    144595
14     131  2021   49.0       160
15     131  2021   50.0       123
16     131  2021   60.0    153680
17     131  2022   32.0    210867
18     131  2022   48.0    288793
19     131  2022   60.0    357008
20     131  2023   32.0    143295
21     131  2023   48.0    196078
22     131  2023   49.0       670
23     131  2023   60.0    302855

In [71]:
dd2 = dd2[dd2["size"] != 600]

In [72]:

fig = px.bar(dd2, x='year', y='Quantity', color='size',
                 hover_data=['size'], text="Company",title =  'total quantity over years per company,size')

fig.show()

In [73]:
px.line(x=[32,36,40,48, 500, 600])

In [81]:
px.line(x=np.log([32,36,40,48, 500, 600]))

In [82]:
df.head(1)

,date,Order_ID,Company,Company_Region,Product_ID,Product,Customer_ID,size,Product Category02,Product Category03,Quantity,unit,price_per_case,year,week_of_year,week_start_dt
0,2021-01-01,6141309,121,South,11829,AVO32CNV2,DMKUT,32.0,CNV,#2,224,case,41.0,2021,53,2020-12-28

In [83]:
dd4 = df.groupby(['Company_Region','year','size','Company']).agg({"Quantity":'sum'}).reset_index()
fig = px.bar(dd4, x='year', y='Quantity', color='Company_Region',
              text="Company_Region",title =  'total quantity over years per Company_Region,size,company')

fig.show()

In [86]:

dd3 = df.groupby(['Company_Region','year','size','Company']).agg({"Quantity":'sum'}).reset_index()
fig = px.bar(dd3, x='year', y='Quantity', color='Company_Region',
              hover_data=['size', 'Company'], text="Company_Region",title =  'total quantity over years per Company_Region,size,company')

fig.show()

In [87]:
fig = px.bar(dd3,
             x='Company_Region',
             y='Quantity',
             color='Company_Region',
             hover_data=['size', 'Company'],
             text="Company_Region",
             title='Total Quantity over Years per Company_Region, Size, Company',
             animation_frame='year')  # Add the slider for year

fig.update_layout(xaxis={'categoryorder':'total descending'})  # Optional: to order categories by total

fig.show()

In [90]:
fig = px.bar(dd3,
             x='Company_Region',
             y='Quantity',
             color='Company_Region',
             hover_data=['size', 'Company'],
             text="Company_Region",
             title='Total Quantity over Years per Company_Region, Size, Company',
             animation_frame='year')  # Add the slider for year

# Set the frame duration (in milliseconds) to slow down the animation
fig.update_layout(xaxis={'categoryorder': 'total descending'},
                  updatemenus=[{
                      'buttons': [
                          {
                              'args': [None, {'frame': {'duration': 2000, 'redraw': True},  # 1000 ms = 1 second per frame
                                              'fromcurrent': True}],
                              'label': 'Play',
                              'method': 'animate'
                          },
                          {
                              'args': [[None], {'frame': {'duration': 0, 'redraw': True}, 'mode': 'immediate'}],
                              'label': 'Pause',
                              'method': 'animate'
                          }
                      ],
                      'type': 'buttons'
                  }])

fig.show()

In [99]:
# last but not least

dates = pd.date_range(start='2024-08-01', periods=8, freq='D')
actual_values = np.random.randint(20, 40, size=8)
predictions = actual_values + np.random.randint(-10, 10, size=8)

data = {'Date': dates,
    'Actual': actual_values,'Prediction': predictions}
df = pd.DataFrame(data)

df

        Date  Actual  Prediction
0 2024-08-01      31          31
1 2024-08-02      25          22
2 2024-08-03      33          37
3 2024-08-04      26          21
4 2024-08-05      36          33
5 2024-08-06      24          21
6 2024-08-07      25          19
7 2024-08-08      21          25

In [101]:
df['difference'] = abs(df['Actual'] - df['Prediction'])

In [102]:
# how to add difference line ?

fig = go.Figure()

fig.add_trace(go.Scatter(x=df['Date'], y=df['Actual'],
                        mode='lines+markers',name=f'Actual'))

fig.add_trace(go.Scatter(x=df['Date'], y=df['Prediction'],
                        mode='lines+markers', name=f'prediction'))

fig.add_trace(go.Scatter(x=df['Date'], y=df['difference'],
                        mode='lines+markers', name=f'difference'))

fig.update_xaxes(title_text='Date', tickformat='%Y-%m-%d',
                tickvals=df['Date'], tickmode='array')

fig.update_layout(title='Actual vs Prediction')

fig.show()